Dockerfile, supervisor.conf
This dockerfile builds a docker container that groups together all astarte
services.
=> Add "all in one" Dockerfile

.gitignore, compose.env, compose/cfssl-config/ca_root_config.json, compose/cfssl-config/csr_root_ca.json, compose/cfssl-config/db_config.json, docker-compose.yml, generate-compose-files.sh
This PR adds an "instant run" system for Astarte via docker-compose (not advised in production). Simply do
```
./generate-compose-files.sh
docker-compose up -d
```
And you're set and ready to go.
=> Add docker-compose and helper files

generate-astarte-credentials, generate-astarte-device-id
These scripts are mostly useful in quick tutorials and to try out Astarte without setting up additional SSOs or external systems.
=> Add useful Python scripts for generating tokens and IDs

compose/vernemq-certs/openssl.cnf, docker-compose.yml, generate-compose-files.sh
Self-signed certificates just won't work
=> Use correct SSL CA for VMQ

doc/mix.exs
We just use it to generate docs
=> mix.exs: relax Elixir version requirement

Dockerfile
1.6.6/OTP21 breaks Astarte's deps
=> Set Elixir version to 1.6.5

doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml, supervisor.conf
=> New pairing fixups

doc/pages/user/035-register_device.md, doc/pages/user/040-connect_device.md
This PR extends and clarifies the way a Device's lifecycle is managed, introduces the concept of Transport and clarifies the relationship between Astarte's SDK(s) and Astarte/MQTT.
=> docs: Improve user documentation for Pairing/Registration/Connection

doc/mix.exs
=> doc: Fix versioning, and add -dev suffix for master

doc/mix.exs
doc/mix.exs: update version number to 0.11.0-dev.
=> Prepare next devel cycle

doc/pages/tutorials/010-astarte_in_5_minutes.md
Ensure versioning is consistent among branches/docs
=> doc: Use 0.10 when pulling images

doc/mix.exs
doc/mix.exs: update version to 0.10.0-beta.1.
=> Prepare 0.10.0-beta.1

doc/mix.exs
Update doc/mix.exs version to 0.10.0-beta.2.
=> Prepare next beta

doc/pages/administrator/001-intro_administrator.md
=> 001-intro_administrator.md: fix typo

doc/pages/architecture/080-mqtt-v1-protocol.md
Add protocol documentation to the architecture doc section.
=> Add Astarte MQTT v1 Protocol

CHANGELOG.md, doc/pages/architecture/070-auth.md, doc/pages/user/010-interacting_with_astarte.md, generate-astarte-credentials
=> Remove explicit authorization delimiters

docker-compose.yml
Add a Grafana image with the astarte datasource plugin installed
=> docker-compose.yml: Add Grafana docker image

CHANGELOG.md, Dockerfile, doc/mix.exs, doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml
Next release will be 0.10.0-beta.3.
=> Prepare next development cycle

README.md
Add links to #astarte on Freenode and Elixir Slack.
=> Add links to IRC and Slack

doc/pages/tutorials/010-astarte_in_5_minutes.md
There are two packages in pip: jwt and PyJWT. The second one is the one we want.
=> 010-astarte_in_5_minutes: fix Python JWT package

doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml
They don't have the patch suffix
=> Fix snapshot versions

CHANGELOG.md, Dockerfile, doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml
Get ready for Astarte v0.10.0-rc.0 release.
=> Prepare v0.10.0-rc.0 release

doc/mix.lock
Update ex_doc to 0.20.1 and all its deps.
=> mix.lock: update ex_doc

README.md
Tell users to use v0.10.0 instead of master.
=> README.md: tell users to use the latest stable version

CHANGELOG.md, Dockerfile, docker-compose.yml
Update CHANGELOG.md, Dockerfile and docker-compose.yml.
=> Prepare 0.10.1 release

doc/pages/user/050-query_device.md
=> 050-query_device: update device details JSON

doc/pages/architecture/030-interface.md, doc/pages/architecture/040-interface_schema.md
has_metadata is not implemented and not planned yet.
=> doc/architecture: remove has_metadata

doc/pages/user/030-manage_interfaces.md
Interface JSON object is returned inside "data".
=> 030-manage_interfaces: fix wrong API response example

CHANGELOG.md, Dockerfile, doc/mix.exs, docker-compose.yml
Update CHANGELOG.md, Dockerfile and docker-compose.yml.
=> Prepare 0.10.2 release

doc/pages/user/035-register_device.md
Add documentation about the ability to reset the registration state of a device.
=> Device unregister docs

.github/workflows/astarte-apps-build-workflow.yaml
Upon PRs, build apps only if the apps build workflow has changed.
=> workflows: Don't do unneeded builds

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/endpoint.ex
Fix https://github.com/astarte-platform/astarte_appengine_api/issues/20
=> endpoint: add a new socket route under /v1/socket

doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml, generate-compose-files.sh
Basically what was left out of the previous PR
=> docs: More tools deprecations

README.md
=> README.md: update latest stable version to 0.10.2

README.md
Change links to apps/astarte_APP_NAME.
=> README.md: stop linking archived repositories

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/mix.lock, apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/interface_view.ex, apps/astarte_realm_management_api/mix.lock
Given the possibility to include hyphens into interface_name, handle the mapping of interface_name to table name.
=> Handle interface name to table name

doc/pages/architecture/030-interface.md
Update documentation: make limitations clear in the interface_name choice.
=> 030-interface: udpate documentation as concerns interface_name

CHANGELOG.md, standard-interfaces/org.astarte-platform.genericsensors.AvailableSensors.json, standard-interfaces/org.astarte-platform.genericsensors.SamplingRate.json, standard-interfaces/org.astarte-platform.genericsensors.Values.json
Provide some ready to use interfaces.
Fix https://github.com/astarte-platform/astarte/issues/86
=> Add some standard interfaces

CHANGELOG.md, apps/astarte_housekeeping/priv/migrations/realm/0003_add_database_retention_ttl_and_policy.sql
Fix Cassandra crash during upgrade
=> Fix database retention realm migration

README.md, doc/pages/tutorials/010-astarte_in_5_minutes.md
In particular, replace the compose bash script with the new Docker Container at astarte/docker-compose-initializer.
=> Improve starter docs

CHANGELOG.md, apps/astarte_pairing/lib/astarte_pairing/engine.ex, apps/astarte_pairing/lib/astarte_pairing_web/metrics.ex, apps/astarte_pairing/lib/astarte_pairing_web/metrics/pairing_instrumenter.ex, apps/astarte_pairing/mix.exs, apps/astarte_pairing/mix.lock
=> pairing: expose registration count metrics

CHANGELOG.md, apps/astarte_housekeeping/lib/astarte_housekeeping_web/router.ex
=> Add health endpoint to Housekeeping

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management_web/router.ex
Add health endpoint to Realm Management
=> Add health endpoint to Realm Management

CHANGELOG.md, apps/astarte_pairing/lib/astarte_pairing_web/router.ex
Add health endpoint to pairing
=> Add health endpoint Pairing

apps/astarte_pairing_api/mix.exs, apps/astarte_pairing_api/mix.lock
=> Release 0.11 pulls libraries from their 0.11 branch

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/metrics/supervisor.ex, apps/astarte_housekeeping/lib/astarte_housekeeping_web/metrics/supervisor.ex, apps/astarte_pairing/lib/astarte_pairing_web/metrics/supervisor.ex, apps/astarte_realm_management/lib/astarte_realm_management_web/metrics/supervisor.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/metrics/supervisor.ex, docker-compose.yml
Expose port 4000 for all the backend services
=> Update services' port number

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/message_tracker/server.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/triggers_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/metrics.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/metrics/data_updater_plant_instrumenter.ex, apps/astarte_data_updater_plant/mix.exs, apps/astarte_data_updater_plant/mix.lock
=> Export DataUpdaterPlant specific metrics with telemetry

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/metrics.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/metrics/trigger_engine_instrumenter.ex, apps/astarte_trigger_engine/mix.exs, apps/astarte_trigger_engine/mix.lock
Add specific metrics to TriggerEngine
=> Export TriggerEngine specific metric with telemetry

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/data_transmitter.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/events_dispatcher.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/room.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/metrics/appengine_instrumenter.ex, apps/astarte_appengine_api/mix.exs
Add specific metrics to AppEngine
=> Export AppEngine specific metric with telemetry

apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
Restore the insertion into the database of server owned individual datastreams.
=> Fix regression on individual datastreams

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/endpoint.ex
=> Remove deprecated not versioned socket route

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/handler.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/rpc/handler.ex, apps/astarte_pairing/lib/astarte_pairing/rpc/handler.ex
Make sure that GenericOKReply always has error = false, and
async_operation defaults to false.
=> proto3 doesn't support defaults, avoid them.

apps/astarte_appengine_api/.dockerignore, apps/astarte_data_updater_plant/.dockerignore, apps/astarte_housekeeping/.dockerignore, apps/astarte_housekeeping_api/.dockerignore, apps/astarte_pairing/.dockerignore, apps/astarte_pairing_api/.dockerignore, apps/astarte_realm_management/.dockerignore, apps/astarte_realm_management_api/.dockerignore, apps/astarte_trigger_engine/.dockerignore
=> Add .dockerignore to all apps

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs
=> Return an object when GETting on object aggregated interfaces

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
=> events_consumer: fix crash when receiving an HTTP 500 response

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/value_match_operators_test.exs
Prevent formatting related failures in the CI.
=> value_match_operators_test: format file

examples/sensor-graph/package.json, examples/sensor-graph/yarn.lock
Signed-off-by: Shubham Wadhwa <shubham.wadhwa@ispirata.com>
=> Updated react-script version

.github/workflows/astarte-apps-build-workflow.yaml, docker-compose.yml, tools/astarte_export/.travis.yml
=> Update to ScyllaDB 3.3.0

.github/workflows/astarte-apps-build-workflow.yaml, docker-compose.yml
=> Update to RabbitMQ 3.8.x

.github/workflows/astarte-apps-build-workflow.yaml
Test Astarte using Cassandra 3.11.6.
=> Update Cassandra to 3.11.6

doc/pages/architecture/030-interface.md, doc/pages/architecture/040-interface_schema.md
Update mappings documentation.
=> Add database_retention_policy/ttl to documentation

doc/pages/architecture/090-database.md
Add Astarte database documentation.
=> Add 090-database.md

doc/pages/architecture/090-database.md
=> 090-database.md: add schema changes documentation

.github/workflows/docs-workflow.yaml, doc/swagger-ui-index.html
This PR ensures that we always generate Swagger UI for API documentations for all API sets.
Fixes #337
=> actions: Add Swagger API generation

doc/pages/administrator/030-installation_kubernetes.md, doc/pages/administrator/040-manual_kubernetes.md, doc/pages/administrator/060-setup_cluster.md, doc/pages/administrator/065-setup_ingress.md, doc/pages/administrator/070-manage_realms.md, doc/pages/administrator/080-upgrade_guide.md, doc/pages/administrator/090-monitoring.md, doc/pages/architecture/010-design_principles.md, doc/pages/architecture/030-interface.md, doc/pages/architecture/040-interface_schema.md, doc/pages/architecture/050-pairing_mechanism.md, doc/pages/architecture/060-triggers.md, doc/pages/architecture/070-auth.md, doc/pages/architecture/080-mqtt-v1-protocol.md, doc/pages/architecture/090-database.md, doc/pages/tutorials/010-astarte_in_5_minutes.md, doc/pages/user/010-interacting_with_astarte.md, doc/pages/user/029-interface_design_guide.md, doc/pages/user/030-manage_interfaces.md, doc/pages/user/040-connect_device.md, doc/pages/user/052-using_channels.md, doc/pages/user/060-using_triggers.md, doc/pages/user/065-managing-groups.md
This PR integrates all needed changes/fixes for 0.11 documentation before it gets released. Individual PRs are referenced in individual commits.
=> Fix documentation for 0.11 (and beyond)

apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, doc/pages/architecture/060-triggers.md, doc/pages/user/050-query_device.md, doc/pages/user/060-using_triggers.md, doc/pages/user/065-managing-groups.md
This includes Triggers and AppEngine, mainly. It also fixes URL references in OpenAPI files.
=> Docs fixes, batch 2

doc/pages/administrator/040-manual_kubernetes.md, doc/pages/administrator/060-setup_cluster.md, doc/pages/administrator/065-setup_ingress.md, doc/pages/tutorials/010-astarte_in_5_minutes.md, doc/pages/user/052-using_channels.md, docker-compose.yml
Update changelog file, docker-compose.yml and make sure documentation always
points to 0.11.0 releated resources and update version numbers.
=> Prepare 0.11.0

CHANGELOG.md
Add v0.11.0 release date to changelog file.
=> Prepare v0.11.0

doc/pages/tutorials/010-astarte_in_5_minutes.md
Make sure users are using recent software versions.
=> doc: add prerequistes checks to Astarte in 5 minutes

apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, doc/pages/user/050-query_device.md
Add metadata to the documentation
=> Update documentation including metadata

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
Add additional configuration options to http actions.
=> Http action advanced config

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/server.ex, doc/pages/architecture/090-database.md
See https://github.com/astarte-platform/astarte_vmq_plugin/pull/16
Fix #305
=> data_updater_plant: add support for device heartbeat

CHANGELOG.md, apps/astarte_appengine_api/mix.exs, apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping_api/mix.exs, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_pairing/mix.exs, apps/astarte_pairing_api/mix.exs, apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management_api/mix.exs, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_trigger_engine/mix.exs, docker-compose.yml, tools/astarte_export/mix.exs, tools/astarte_import/mix.exs
Bump version number to 0.11.1.
=> Prepare next 0.11 dev cycle

apps/astarte_appengine_api/test/astarte_appengine_api_web/channels/rooms_channel_test.exs
=> rooms_channel_test: add missing watch_cleanup

apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
There was a minor issue in http_custom_headers change, fix it.
=> Fix minor bug in EventsConsumer

apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
Fix a minor bug involving an impossible matching.
=> trigger_engine: fix wrong match

examples/javascript-sensors-viewer/astarte.js, examples/javascript-sensors-viewer/index.html
Showing sensor ID, Name, Period and Value
Uses "AvailableSensors", "SamplingRate" and "Values" interfaces in example
Signed-off-by: Shubham Wadhwa <shubham.wadhwa@ispirata.com>
=> This example is a simple sensor viewer implemented in Javascript

examples/sensor-channels/package-lock.json, examples/sensor-channels/package.json, examples/sensor-channels/public/index.html, examples/sensor-channels/src/apiHandler.js, examples/sensor-channels/src/assets/css/cast.css, examples/sensor-channels/src/components/CredentialsModal.jsx, examples/sensor-channels/src/components/SensorData.jsx, examples/sensor-channels/src/components/SensorDataHandler.jsx, examples/sensor-channels/src/components/SensorDisplay.jsx, examples/sensor-channels/src/index.js
Use WebSocket to connect Astarte Channel Displaying device status,
real time status and data 
Only "org.astarte-platform.genericsensors.Values" interface is used
Fix #102
Signed-off-by: shubham wadhwa <shubham.wadhwa@ispirata.com>
=> Added React example for Astarte Channel. 

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer/supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/consumers_supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater.ex
See https://github.com/astarte-platform/astarte/pull/377 and https://github.com/astarte-platform/astarte/issues/375
=> Forward port PR 377 to master

examples/sensor-samplingrate/package-lock.json, examples/sensor-samplingrate/package.json, examples/sensor-samplingrate/public/index.html, examples/sensor-samplingrate/src/apiHandler.js, examples/sensor-samplingrate/src/assets/css/cast.css, examples/sensor-samplingrate/src/components/CredentialsModal.jsx, examples/sensor-samplingrate/src/components/SensorItem.jsx, examples/sensor-samplingrate/src/components/SensorSamplingUpdate.jsx, examples/sensor-samplingrate/src/components/SensorViewer.jsx, examples/sensor-samplingrate/src/index.js
Displays Sensor rate and status data
Can Update status and sampling period configuration
Uses "SamplingRate", "Values" interfaces in this example
Fix #99
Signed-off-by: Shubham Wadhwa <shubham.wadhwa@ispirata.com>
=> Add ReactJS sensor sampling Rate example

apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml
=> astarte_pairing_api: document initial_introspection payload

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
The data updater was crashing when the data couldn't be pushed to the device.
This makes sure that queue keep flowing, the device will resend /emptyCache
anyway since we ask for a clean session.
Also fix previous typo (s/Logger.warning/Logger.warn/g) that could have
introduced crashes in edge cases.
=> data_updater: discard emptyCache if data can't be pushed to the device

compose/astarte-dashboard/config.json
Let the Astarte dashboard figure out which are the components URL
Signed-off-by: Mattia <mattia.pavinati@gmail.com>
=> Update dashboard config

.github/workflows/docs-workflow.yaml
Build documentation when we branch out
=> Run docs workflow also on branch creation

doc/pages/architecture/090-database.md
=> 090-database.md: document new metadata column

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/mix.exs
Fix AMQP triggers installation
=> realm_management: decode the JSON action string before matching it

apps/astarte_housekeeping/lib/astarte_housekeeping/config.ex, apps/astarte_pairing/lib/astarte_pairing/config.ex, apps/astarte_realm_management/lib/astarte_realm_management/config.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/config.ex
Some of the default port values set by Skogsra were wrong. Set them to the rigtht value (i.e. 4000).
=> Fix default ports

doc/pages/user/050-query_device.md, doc/pages/user/052-using_channels.md
Help users to find out that Astarte Channels == WebSockets.
=> Mention websockets

apps/astarte_appengine_api/mix.lock
cd apps/astarte_appengine_api && mix.deps get
=> mix.lock: add castore

docker-compose.yml
Add the ability to query the health check on the broker
=> docker-compose: expose port 8888 on VerneMQ

tools/astarte_e2e/lib/astarte_e2e/config.ex, tools/astarte_e2e/lib/astarte_e2e/config/bamboo_mail_adapter.ex
=> Support Sendgrid for sending mails

.github/workflows/astarte-end-to-end-test-workflow.yaml, tools/astarte_e2e/lib/astarte_e2e/config.ex
=> Drop `ASTARTE_` prefix from env vars

tools/astarte_e2e/lib/astarte_e2e_web/plug/health_plug.ex
=> Add health enpoint to Astarte end-to-end

tools/astarte_e2e/lib/astarte_e2e/config.ex, tools/astarte_e2e/lib/astarte_e2e/config/normalized_mail_address.ex
=> Include the sender's name within alert mails

tools/astarte_e2e/config/prod.exs, tools/astarte_e2e/lib/astarte_e2e/client.ex, tools/astarte_e2e/lib/astarte_e2e/service_notifier.ex
=> E2E reduce noise in logs

tools/astarte_e2e/config/prod.exs, tools/astarte_e2e/lib/astarte_e2e/service_notifier.ex, tools/astarte_e2e/lib/astarte_e2e/service_notifier/email.ex
+ add date and time to notification mails
+ when the service status returns up, notify the user
=> E2e improve mail notifications

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
=> trigger_engine: correctly handle binaryblob values in triggers

doc/pages/administrator/095-advanced-operations.md
Provide a guide to manually delete an interface
=> doc: add 095-advanced-operations.md

examples/sensor-channels/package-lock.json, examples/sensor-channels/package.json, examples/sensor-samplingrate/package-lock.json, examples/sensor-samplingrate/package.json
Fix vulnerabilities found in the dependencies tree of each
Astarte javascript example.
Signed-off-by: Mattia <mattia.pavinati@ispirata.com>
=> Update javascript dependencies in Astarte examples

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex
=> RM: Disallow `/*` match path when using value_change* trigger

README.md
git clone and use release-1.0 branch.
=> README.md: add missing -b release-1.0

doc/pages/architecture/060-triggers.md
Make "Astarte Flow" in triggers page a link to Astarte Flow
documentation.
=> doc: add link to Astarte Flow documentation

doc/mix.exs, doc/pages/administrator/030-installation_kubernetes.md, doc/pages/administrator/040-manual_kubernetes.md, doc/pages/upgrade/000-upgrade_index.md, doc/pages/upgrade/010-upgrade_010_011.md, doc/pages/upgrade/020-upgrade_011_10.md, doc/pages/upgrade/030-upgrade_10.md
Document Operator's upgrade procedure:
+ create a dedicated `upgrade` section
+ document upgrade procedure for :
+ 0.10 --> 0.11
+ 0.11 --> 1.0
+ \>= 1.0
+ minor fixes
=> Document upgrade procedure

doc/pages/upgrade/020-upgrade_011_10.md, doc/pages/upgrade/030-upgrade_10.md
+ fix commands for 0.11 --> 1.0 upgrades
+ add info to enable Flow after upgrading Astarte >= 1.0
=> Improve doc for Astarte upgrades

doc/pages/tutorials/010-astarte_in_5_minutes.md
+ Bump interface major referenced in trigger file
+ Remove procedure for building stream-qt5-test
=> Update Astarte in 5 minutes doc page

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/mix.lock, apps/astarte_trigger_engine/mix.lock
=> appengine: encode binaryblob values with Base64 even in aggregates

doc/pages/user/090-troubleshooting.md, doc/pages/user/095-known_issues.md
Document some v1.0 known issues
=> docs: add 095-known_issues.md page

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/version_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/router.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/version_view.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/version_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/version_view.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/controllers/version_controller.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/router.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/views/version_view.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/version_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/router.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/version_view.ex
Return the application version to authenticated users
=> Add /version endpoint in API applications

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/docs-workflow.yaml, .github/workflows/pr-container-build-workflow.yaml
Use action maintained by erlef + pinpoint ubuntu version (use 18.04).
=> Fix CI: use erlef/setup-beam 1.7.0 instead of actions/setup-elixir 1.5.0

CHANGELOG.md, doc/pages/administrator/020-prerequisites.md
Operator provides basic support for Cassandra. Document its removal in a near future.
=> Document future removal of Cassandra support from Operator

doc/pages/administrator/095-advanced-operations.md
The command was not precise. Fix it
=> advanced-operations: fix command to backup devices ca

CHANGELOG.md
Add missing `### Fixed` to 0.11.5.
=> Add missing title to CHANGELOG.md file

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/application.ex, apps/astarte_housekeeping/lib/astarte_housekeeping.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/application.ex, apps/astarte_pairing/lib/astarte_pairing.ex, apps/astarte_pairing_api/lib/astarte_pairing_api/application.ex, apps/astarte_realm_management/lib/astarte_realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/application.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/application.ex
Puts "Starting application v#{@app_version}." when the application is
starting.
=> Print app version when starting

doc/pages/tutorials/010-astarte_in_5_minutes.md
Use git clone -b instead of master.
=> Minor fixes to Astarte in 5 Minutes

doc/pages/administrator/001-intro_administrator.md, doc/pages/architecture/001-intro_architecture.md, doc/pages/tutorials/010-astarte_in_5_minutes.md, doc/pages/user/001-intro_user.md
v1.0 is stable now, remove all disclaimers.
=> doc: remove "development version" disclaimer

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/server.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/telemetry.ex
Measure how long it takes to handle data.
=> DUP: add handle_data duration to metrics

doc/pages/upgrade/030-upgrade_10.md
CRDs are not updated when running `helm upgrade`. Provide the steps to address this problem.
=> Document how to update CRDs when upgrading Astarte Operator

doc/pages/administrator/095-advanced-operations.md
Be more specific in documenting how to delete data on individual properties.
=> advanced-operations: document how to delete for individual properties

README.md, apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, doc/pages/administrator/060-setup_cluster.md, doc/pages/administrator/064-setup_astartedefaultingress.md, doc/pages/tutorials/010-astarte_in_5_minutes.md
Merge relevant changes introduced in release-1.0 branch into master.
=> Forward port v1.0 to master

doc/pages/administrator/095-advanced-operations.md
Fix leftovers in cqlsh queries and avoid confusion.
=> advanced-operations: fix keys in queries

SECURITY.md
Add security policy for 0.11, as suggested from GH guidelines.
=> 0.11 security policy

SECURITY.md, doc/pages/architecture/070-auth.md
Forward port SECURITY.md file.
=> 1.0 fwd port security policy

.github/pull_request_template.md, .github/pull_request_template.md.license, CODE_OF_CONDUCT.md, CONTRIBUTING.md
Add PR template, Code of Conduct and CONTRIBUTING document.
=> Add project documents

.github/pull_request_template.md, .github/pull_request_template.md.license, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/realms.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/fallback_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/realm_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/error_view.ex, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/engine/mapping_updates.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/interfaces.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_controller.ex, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs, doc/pages/administrator/060-setup_cluster.md, doc/pages/administrator/095-advanced-operations.md, doc/pages/architecture/070-auth.md
This PR merges a number of fixes that has been merged into release-1.0.
=> Forward port changes from v1.0

CHANGELOG.md, doc/pages/upgrade/000-upgrade_index.md, doc/pages/upgrade/020-upgrade_011_10.md, doc/pages/upgrade/030-upgrade_100_10x.md
=> Forward port 1.0 into master

doc/pages/tutorials/010-astarte_in_5_minutes.md
Signed-off-by: Rajesh Reddy <rajesh.reddy@secomind.com>
=> Dashboard port info added in the install astarte document section

CHANGELOG.md, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/trigger_view.ex
=> Display the `policy` field when a trigger is returned

doc/mix.exs, doc/pages/administrator/070-manage_realms.md
- update links to the source of each documentation page
- update link to the homepage of the component
- fix a broken link to API docs
=> Minor fixes for documentation pages

.github/workflows/astarte-apps-build-workflow.yaml, docker-compose.yml
Update both to the latest versions.
=> Update ScyllaDB and Cassandra

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/fallback_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/error_view.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_by_alias_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_by_group_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/interface_values_by_device_alias_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/interface_values_by_group_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/interface_values_controller_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
Handle the error in the fallback controller.
Also add relevant entries in device and controller tests.
A new interface was added to a test device to trigger the error.
Relevant tests were updated to reflect this change.
=> AppEngine: handle `:unexpected_object_key`

CHANGELOG.md, apps/astarte_appengine_api/mix.exs, apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping_api/mix.exs, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_pairing/mix.exs, apps/astarte_pairing_api/mix.exs, apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management_api/mix.exs, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_trigger_engine/mix.exs, doc/mix.exs, doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml, tools/astarte_e2e/mix.exs, tools/astarte_export/mix.exs, tools/astarte_import/mix.exs
Bump all version numbers in order to start with Astarte 1.2.0 development.
=> Prepare v1.2.0 dev

.github/workflows/docs-workflow.yaml
Partially reverts changes introduced in #789.
=> Docs workflow: do not fail when setting up Elixir

doc/pages/architecture/030-interface.md, doc/pages/architecture/060-triggers.md, doc/pages/architecture/070-auth.md, doc/pages/architecture/080-mqtt-v1-protocol.md, doc/pages/tutorials/010-astarte_in_5_minutes.md
- Docker compose ps command added to 'Astarte in 5 minutes'
- Fixed link in Interfaces page
- Removed code section in Interfaces > Datastream specific features
- Fixed label of code block in trigger page
- Fixed a term in the Authorization page
=> Fixes to astarte docs

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/astarte-end-to-end-test-workflow.yaml, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/mix.exs, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping_api/mix.exs, apps/astarte_pairing/mix.exs, apps/astarte_pairing_api/mix.exs, apps/astarte_realm_management/config/config.exs, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management_api/mix.exs, apps/astarte_trigger_engine/mix.exs, tools/astarte_device_fleet_simulator/mix.exs, tools/astarte_e2e/mix.exs, tools/astarte_e2e/mix.lock, tools/astarte_export/mix.exs, tools/astarte_import/mix.exs
=> Update to Elixir 1.15.x

doc/pages/tutorials/010-astarte_in_5_minutes.md
- Fixed version tag of astarte-stream-qt5-test
- Fixed mistakes in interfaces section of 'Astarte in 5 minutes'
=> Review 'Astarte in 5 minutes'

docker-compose.yml
looks like the broker alias is needed too
=> fix(docker-compose): also add broker to traefik aliases

README.md
Tell users that v1.1 is stable now and v1.2 is dev.
=> README: update info about latest stable version

README.md
=> Update 1.1 README.md

doc/pages/architecture/040-interface_schema.md
=> Allowed patterns in interface schema

doc/pages/tutorials/010-astarte_in_5_minutes.md
Change old `docker-compose` command to new `docker compose` in `Astarte in 5 minutes` tutorial.
Closes #820
=> Change docker-compose in Astarte tutorial

tools/astarte_e2e/README.md
=> AstarteE2E: update README.md

tools/astarte_import/lib/astarte/import/populatedb.ex
- Changing the Database.connec function parameters
- Fix data type reception_timestamp
=> AstarteImport: fix datetime and database connect error

apps/astarte_appengine_api/Dockerfile, apps/astarte_appengine_api/mix.exs, apps/astarte_data_updater_plant/Dockerfile, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/Dockerfile, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping_api/Dockerfile, apps/astarte_housekeeping_api/mix.exs, apps/astarte_pairing/Dockerfile, apps/astarte_pairing/mix.exs, apps/astarte_pairing_api/Dockerfile, apps/astarte_pairing_api/mix.exs, apps/astarte_realm_management/Dockerfile, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management_api/Dockerfile, apps/astarte_realm_management_api/mix.exs, apps/astarte_trigger_engine/Dockerfile, apps/astarte_trigger_engine/mix.exs
Update Elixir version in order to be consistent with CI steps.
=> Apps: upgrade Elixir to 1.15

apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml
=> Fix swagger for pairing api

apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml
- fix `TriggerDeliveryPolicyErrorHandler` schema
- add explicit 404 errors
=> Update Realm Management OpenAPI

.github/pull_request_template.md
Add more detail to the PR template. Based on K8s' one.
=> Contribution: revamp PR template

doc/pages/administrator/095-advanced-operations.md, doc/pages/user/050-query_device.md
Device deletion was introduced, but not documented. Fix this.
None
```docs
```
=> Docs: document device deletion

flake.lock, flake.nix
Updates the nix lock. Needed for the newer elixir and erlang versions defined in the .tool-versions
```docs
```
=> chore(nix): update inputs

doc/pages/development-guide/001-dev_guide.md
Add a guide on how to make changes to Astarte, inspired by other OSS projects (k8s, rust, helix,...)
=> Docs: add a development guide

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/interface_value.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/interface_value_test.exs
- Extract `cast_value` functions from `device.ex` file into `InterfaceValue` module
- Added tests for `cast_value` functions
=> AppEngine: refactor `device.ex` file

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/interface_value.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/interface_value_test.exs
Forward-port changes from release-1.1 to release-1.2
Done with the commands
```
git checkout release-1.2
git merge --no-ff release-1.1
```
=> Forwardport release 1.1 into release-1.2

.github/workflows/astarte-end-to-end-test-workflow.yaml, .github/workflows/pr-container-build-workflow.yaml
Currently, we're not taking into account the new position of the `Dockerfile` (see #956). Fix this.
Also, do a small astartectl bump while we're at it.
none
=>  Workflows: fix test container build workflow 

doc/pages/architecture/090-database.md
The documentation on the database schema for Astarte is a bit outdated and doesn't report correct information.
The PR updates the columns of the database tables presented on the Astarte Database page to match the actual queries run to create the tables.
It also adds some descriptions to better explain the setup process of the database tables, and the typical values that are inserted when initializing Astarte or a new ScyllaDB keyspace.
The PR doesn't currently apply comprehensive changes to the documentation page, such as describing all queries that are run by Astarte services on the database.
=> Update documentantion on database structure

.github/workflows/astarte-end-to-end-test-workflow.yaml
docker-compose is deprecated an now compose is it's own module inside the docker CLI
=> Fix docker compose command in CI

.github/workflows/astarte-end-to-end-test-workflow.yaml
done with
```
git checkout release-1.2
git merge --no-ff release-1.1
```
=> Forwardport release 1.1

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/astarte-end-to-end-test-workflow.yaml, .github/workflows/publish-release-to-dockerhub-workflow.yaml, .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml
Workflows for pushing images to dockerhub did not work as intended, as the dependency on tests was not correctly specified. This means they were broken.
Use workflow_call events to specify dependencies and allow to publish images only if tests are passed.
Fixes (none)
```docs
```
=> Workflows: ensure dependencies on tests before publishing images

flake.lock, flake.nix
=> chore(flakes): flake tool version and update

tools/astarte_import/lib/astarte/import/populatedb.ex
Enhancements to state handling in `tools/astarte_import/lib/astarte/import/populatedb.ex:`
- Refactored the `got_end_of_object_fun function` to properly destructure and update the State structure.
- Ensured the `last_seen_reception_timestamp` is correctly updated within the `got_end_of_property_fun` function.
Improvements to structure handling:
* [`tools/astarte_import/lib/astarte/import/populatedb.ex`](diffhunk://#diff-c44ae038ffd4df03c9927a99b57c6d54f9cd97ae8d8cadfde826c67b8188d6beL333-R342): Modified the `got_end_of_object_fun` function to correctly destructure the `State` structure and update its fields.
* [`tools/astarte_import/lib/astarte/import/populatedb.ex`](diffhunk://#diff-c44ae038ffd4df03c9927a99b57c6d54f9cd97ae8d8cadfde826c67b8188d6beR365-R368): Ensured the …
=> Refactor: streamline state handling in populatedb

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
The metric was inadvertently removed when switching to Mississippi as message engine.
Bring it back. Also, we need to define what to do when we're discarding messages (during device deletion).
We did not show the `handle_data_duration_ms` metric due to an unintentional error in #995.
Fixes #
```docs
```
=> DUP: show again the data duration time metric

tools/astarte_import/lib/astarte/import.ex
Enhancements to XML and attribute value handling:
- Added support for importing never-connected devices by handling missing attribute values more gracefully.
- Updated to_boolean/1 to treat empty strings as false, improving boolean value parsing.
- Added default values for missing attribute values in multiple xml_event/3 functions, ensuring consistent behavior when attributes are absent.
Code cleanup:
- Removed unused to_date_or_nil/1 functions, simplifying the codebase.
The primary goal of this change is to enhance the Astarte import process by supporting devices that have never been connected, and improving the handling of missing attributes in XML data. This ensures more reliable imports, even when device data is incomplete.
Fixes #1040 
Please review the changes in import.ex for …
=> Astarte import: Add support never-connected devices import

tools/astarte_export/README.md
Explain to new users of Astarte Export what export file formats they can expect.
Fixes #
Update README.md with a new example of an exported XML file.
```docs
```
=> Astarte Export: Update README.md

doc/pages/development-guide/001-dev_guide.md
Add informations to properly use dev-mode and `astarte_dev_tool`
Addition of documentation required for:
- the use of dev-mode
- the use of `astarte_dev_tool`
=> add information to dev-mode and astarte_dev_tool

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/astarte-end-to-end-test-workflow.yaml
=> chore(porting): forward port release-1.1 to release-1.2

apps/astarte_realm_management/lib/astarte_realm_management/astarte/kv_store.ex, apps/astarte_realm_management/lib/astarte_realm_management/astarte/realm.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/individual_datastream.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/individual_properties.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/interface.ex, apps/astarte_realm_management/lib/astarte_realm_management/uuid.ex
Based on #1076, see that for context.
Adds necessary ecto schemas to `astarte_realm_management`.
=> feat(ecto) add ecto schemas to `realm_management`

apps/astarte_appengine_api/lib/astarte_appengine_api/device/astarte_value.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/name.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
port all select queries in the appengine Device module to exandra
Fixes #
```docs
```
=> refactor(appengine): port Device select queries to exandra

apps/astarte_appengine_api/lib/astarte_appengine_api/device/astarte_value.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/name.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
depends on #1086
Fixes #
```docs
```
=> refactor(appengine): port Device update queries to exandra

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Moves `delete_interface` to `Exandra` and `Ecto`
Fixes #
=> refactor(RM): move `delete_interface`

apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
backport of #1044, as now we need the tests passing with exandra on 1.2
Fixes #
```docs
```
=> BACKPORT: test(appengine): consistently define endpoint types

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
refactor(appengine): port Device update queries to exandra
add log in case of record not found (affected rows = 0)
Clean up unused params
=> refactor(appengine): port Device delete queries to exandra

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
based on #1101 
moves `install_trigger` to use `exandra` and `ecto`
=> refactor(RM): move install_trigger

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Based on #1111 
Moves `delete_trigger_policy` to `exandra` and `ecto`
=> refactor(RM): move delete_trigger_policy

apps/astarte_appengine_api/lib/astarte_appengine_api/health.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/room.ex
Add some other CQex select queries that have escaped round one
=> (APPENGINE) Convert CQex queries to exandra

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
~depends on #1109~
~depends on #1110~
Fixes #
```docs
```
=> refactor(appengine): port insert_values_to_db inserts to exandra

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/realms/individual_property.ex
depends on #1114
Fixes #
```docs
```
=> refactor(appengine): port insert_path_into_db to exandra

apps/astarte_appengine_api/lib/astarte_appengine_api/groups/queries.ex
[(appengine) Add missing keyspace encoding for check_valid_device_for_group
=> (appengine) Add missing keyspace encoding

apps/astarte_pairing/lib/astarte_pairing/queries.ex
Porting all Xandra SELECT to Exandra
- check_astarte_health (select count())
link:
https://www.notion.so/seco-mind/Move-all-SELECT-queries-with-Xandra-to-Exandra-1a0c537dba7f80f3ad26f86d236f977c?pvs=4
=> refactor(pairing): move xandra select to exandra

apps/astarte_pairing/lib/astarte_pairing/queries.ex
A regression was introduced in 0e0452e where an undefined function is called in case the database is not available during an healthcheck. Fix it.
=> Pairing: don't crash on health check when db isn't available

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/trigger_policy/queries.ex
Move Xandra Select to Exandra:
- retrieve_policy_name
=> refactor(dup): move xandra select to exandra

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
Porting all UPDATE queries with Xandra to Exandra
=> refactor(DUP): move xandra update to exandra

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex
Fixed an issue where the `realm_name` was being encoded twice.
=> fix(RM): avoid double encoding of `realm_name `

apps/astarte_realm_management/lib/astarte_realm_management/c_system.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
- Fixed the `@spec` annotations to ensure accurate type definitions
- Removed unused imports across the codebase
=> fix(RM): Correct `@spec` annotations and remove unused imports

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/supervisor.ex
The RPC server supervisor was a regular supervisor, and RPC server distribution was handled only by `Horde.Registry`.
This could be a problem in case of net splits or downscales, the server could die without any supervisor trying to bring it back up.
This PR changes the `RPC` supervisor into a `Horde.DynamicSupervisor`. When started, the supervisor first looks for other RPC servers already started, if none is found, tries to start a new one. This is useful in case of net splits to allow for high availability, by abstracting the supervision tree of the RPC server and distribute it across all DUP replicas in a cluster.
=> feat(DUP): Dynamically supervise `RPC` server

CHANGELOG.md, apps/astarte_appengine_api/mix.exs, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping_api/mix.exs, apps/astarte_pairing/mix.exs, apps/astarte_pairing_api/mix.exs, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management_api/mix.exs, apps/astarte_trigger_engine/mix.exs, docker-compose.yml
As title says.
The E2E CI will break as `1.2.1-alpha.0` docker images are not available until we tag the release.
=> Prepare 1.2.1-alpha.0 release

CHANGELOG.md
The PR reports the changes occurred in the feature branch in the CHANGELOG file.
This change is to ensure that we track at least a summary of the work that has been done while reworking the RPC system between Astarte services.
=> Add changes to CHANGELOG.md

apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping/mix.lock, apps/astarte_housekeeping/test/astarte_housekeeping/engine_test.exs, apps/astarte_housekeeping/test/astarte_housekeeping/queries_test.exs, apps/astarte_housekeeping/test/astarte_housekeeping/rpc/amqp_server_test.exs, apps/astarte_housekeeping/test/helpers/db_test_helper.ex, apps/astarte_housekeeping/test/test_helper.exs
Rationalize and expand queries test
Add new test dependencies
Clean up queries file: Db errors handling have been moved to the parent function
=> HK Rewrite queries tests

apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex, apps/astarte_trigger_engine/mix.lock, apps/astarte_trigger_engine/test/events_consumer_test.exs, apps/astarte_trigger_engine/test/support/cases/trigger.ex, apps/astarte_trigger_engine/test/support/fixtures/simple_event.ex, apps/astarte_trigger_engine/test/support/fixtures/trigger.ex, apps/astarte_trigger_engine/test/support/helpers/events_consumer.ex, apps/astarte_trigger_engine/test/support/helpers/trigger.ex
depends on #1204
Fixes #
```docs
```
=> test(te): init events_consumer tests

apps/astarte_trigger_engine/lib/astarte_trigger_engine/policy/impl.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/policy/policy.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/policy/state.ex, apps/astarte_trigger_engine/mix.exs, apps/astarte_trigger_engine/test/policy/policy_test.exs, apps/astarte_trigger_engine/test/support/cases/policy.ex, apps/astarte_trigger_engine/test/support/fixtures/policy.ex
- use property testing to test core policy behavior
- rework (most of the) example integration tests to be more generic
depends on #1214
Fixes #
```docs
```
=> refactor(te): extract policy logic into its own module

apps/astarte_trigger_engine/test/astarte_trigger_engine_web_test.exs, apps/astarte_trigger_engine/test/support/helpers/plug.ex
- add test for health plug, which should be fixed when the data access health check is fixed
- add test for metrics plug
- test that other endpoints return 404
depends on #1217
Fixes #
```docs
```
=> test(te): add trigger_engine_web tests

doc/pages/architecture/090-database.md
partial backport of https://github.com/astarte-platform/astarte/pull/968
applies changes to the database documentation according to database changes in version 1.2
partially fixes https://github.com/astarte-platform/astarte/issues/1227
```docs
```
=> doc: update database schemas for release-1.2

.github/workflows/pr-size-based-label.yaml
Added CI to add label referring to the size of a PR
=> Add CI for PR size-based labels

apps/astarte_pairing_api/test/astarte_pairing_api/agent/agent_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api/credentials/credentials_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api/health/health_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api/info/info_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api_web/auth/auth_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api_web/controllers/agent_controller_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api_web/controllers/device_controller_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api_web/controllers/version_controller_test.exs
Update all tests in the Astarte Pairing API to run in async mode
=> test(PAIRING API): Update all tests to run in async mode

docker-compose.yml
Introduces the selinux labels in docker compose
more informations here https://docs.docker.com/engine/storage/bind-mounts/#configure-the-selinux-label
=> fix(docker): security patch docker

apps/astarte_realm_management_api/test/astarte_realm_management_api/devices/devices_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/health/health_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/realm_config/realm_config_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/amqp_action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/http_action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/policies/policy_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/trigger_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/triggers_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/device_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_version_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/realm_config_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_policy_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/version_controller_test.exs, apps/astarte_realm_management_api/test/support/cases/conn_case.ex, apps/astarte_realm_management_api/test/support/cases/data_case.ex, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock_db.ex
Update all tests on Realm Management API to run in async mode, in order to achieve faster execution.
=> test(RM API): Allow concurrent execution of tests

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_v2_reading_test.exs, apps/astarte_appengine_api/test/support/cases/device.ex, apps/astarte_appengine_api/test/support/helpers/device.ex, apps/astarte_appengine_api/test/support/interface_update_generators.ex, apps/astarte_appengine_api/test/support/interface_values_retrieveal_generators.ex, apps/astarte_appengine_api/test/test_helper.exs
fix downsample not working for object aggregates and add property tests for it
depends on #1267
```docs
```
=> fix(appengine): downsample for object aggregates

apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/non_negative_integer_or_unset_type.ex, apps/astarte_housekeeping_api/test/astarte_housekeeping_api/realms/realms_test.exs, apps/astarte_housekeeping_api/test/astarte_housekeeping_api_web/controllers/realm_controller_test.exs, apps/astarte_housekeeping_api/test/astarte_housekeeping_api_web/plugs/plug_test.exs, apps/astarte_housekeeping_api/test/support/helpers/astarte_housekeeping_mock.ex, apps/astarte_housekeeping_api/test/support/helpers/astarte_housekeeping_mock_db.ex
- Refactor test organization using `describe` blocks for better structure
- Group property-based tests into a single test to address flakiness caused by creating multiple realms with the same name
- Update mock responses to support both synchronous and asynchronous testing scenarios
- Add new metric-related tests
- Mark unused code in `non_negative_integer_or_unset_type` to exclude it from Coveralls coverage analysis
=> test(HK API): Enhance test coverage and stability

.github/workflows/astarte-apps-build-workflow.yaml, codecov.yml
Codecov used to upload coverage files and consider those as the result of the whole project result
This PR adds codecov configuration file to set up components and improve coverage reports:
=> ci: codecov components

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/amqp_options_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/payloads_decoder_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/dup_device_delete_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/triggers_handler_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/value_match_operators_test.exs, apps/astarte_data_updater_plant/test/support/database_test_helper.exs, apps/astarte_data_updater_plant/test/test_helper.exs
make dup tests async
change db initialization to accept realm
move non asynchronous test
=> Dup async tests

apps/astarte_data_updater_plant/.formatter.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/payloads_decoder_test.exs
first iteration for removing all hardcoded values from DUP tests
Fixes #
```docs
```
=> test(dup): avoid hardcoded values in `PayloadsDecoder` tests

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/interface_test.exs
Based on #1296,
Adds test for `forget_interfaces/2` function, testing that forgotten interfaces are removed from device state cache.
=> test(DUP): `Core.Interface.forget_interfaces/2`

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/interface_test.exs
Based on #1294 
Adds the test for `extract_expected_types/4`, testing that the function correctly extracts the value type from an endpoint
=> test(DUP): test `extract_expected_types/4`

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/application.ex
leftover warning
Fixes #
```docs
```
=> chore: fix warnings

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/queries_test.exs, apps/astarte_data_updater_plant/test/support/helpers/database.ex, apps/astarte_data_updater_plant/test/test_helper.exs
init tests for untested functions in the Queries module. Part 1/2
depends on #1306
```docs
```
=> [SDTT-374] test(dup): queries tests part 1

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/queries_test.exs, apps/astarte_data_updater_plant/test/support/cases/device.ex, apps/astarte_data_updater_plant/test/support/helpers/database.ex, apps/astarte_data_updater_plant/test/test_helper.exs
init tests for untested functions in the Queries module. Part 2/2
depends on #1307
```docs
```
=> [SDTT-374] test(dup): queries tests part 2

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/introspection_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/introspection_handler_test.exs
Extract `handle_introspection` function into a new module
Add tests
Remove unused alias from `impl.ex`
Fixes #
```docs
```
=> refactor(DUP): move handle_introspection to its own module

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/introspection_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/introspection_handler_test.exs
Extract handle_introspection function into a new module
Add tests
Remove unused alias from impl.ex
Fixes #
```docs
```
=> refactor(DUP): move handle_introspection to it's own module

apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/devices/devices.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/devices/queries.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/devices/devices_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/device_controller_test.exs, apps/astarte_realm_management_api/test/support/cases/device.ex, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock.ex, apps/astarte_realm_management_api/test/support/helpers/device.ex
Perform `delete_device` directly on the api service.
Update tests to work with new database helpers.
Fixes #
```docs
```
=> feat(RM): remove delete_device RPC

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management/test/astarte_realm_management/interfaces_test.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/core.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/interfaces.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/queries.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_controller_test.exs, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock.ex
depends on #1359 
Fixes #
```docs
```
=> refactor(rm): remove delete_interface RPC

.github/workflows/publish-release-to-dockerhub-workflow.yaml, .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml, .github/workflows/publish-tool-release-to-dockerhub-workflow.yaml, .github/workflows/publish-tool-snapshot-to-dockerhub-workflow.yaml
- Fixed and updated version of GH actions
- Added metadata labels and annotations
=> Automate metadata tagging of images

.github/workflows/fast-forward.yaml, .github/workflows/pr-fast-forward-check.yaml
- add fast-forward check which marks a non up to-date branch in the ci
- add the fast-forward action which allows fast-forwarding a branch from those with write permissions. this is essentially equivalent to rebase and merge but without rebasing, and thus allows us to keep our commits signed
Fixes #
```docs
```
=> ci: add fast-forward action

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer/supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/consumers_supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/cache.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/cached_path.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/interface.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/payloads_decoder.ex
- fix dialyzer errors
```docs
```
=> fix(DUP):  dialyzer errors

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/introspection_handler_test.exs, apps/astarte_data_updater_plant/test/support/helpers/data_updater.ex
Adds an integration test to test for correct introspection management
Fixes #
```docs
```
=> test(dup): device introspection

apps/astarte_realm_management/mix.lock
Updates data_access in realm management
This has the side effect of solving all dialyzer errors in realm_management
=> chore(rm): update data_access

.github/workflows/fast-forward.yaml, .github/workflows/pr-fast-forward-check.yaml
- add fast-forward check which marks a non up to-date branch in the ci
- add the fast-forward action which allows fast-forwarding a branch from those with write permissions. this is essentially equivalent to rebase and merge but without rebasing, and thus allows us to keep our commits signed
Fixes #
```docs
```
=> chore: forward port #1400

apps/astarte_appengine_api/test/astarte_appengine_api_web/auth/auth_test.exs
=> chore(appengine): fix typo

apps/astarte_appengine_api/mix.exs, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_pairing/mix.exs, apps/astarte_realm_management/mix.exs, apps/astarte_trigger_engine/mix.exs, docker-compose.yml
Astarte components and their docker images use the 1.3 version for the release-1.3 branch
```docs
```
=> chore: update Astarte components and Docker images to version 1.3 for release-1.3 branch

apps/astarte_trigger_engine/lib/astarte_trigger_engine/health.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/plug/health_plug.ex, apps/astarte_trigger_engine/mix.exs, apps/astarte_trigger_engine/mix.lock
Previously, the health check only verified database connectivity via
DataAccess. This update also includes a check to see if AMQP connection is setup correctly.
Update astarte_data_acces and astarte_core to release-1.3.
Fixes #
```docs
```
=> refactor(trigger engine): expand health check to include RabbitMQ connection check

apps/astarte_pairing/lib/astarte_pairing/application.ex
Remove `Xandra.Cluster` from trigger engine's supervision tree as it is no longer needed.
```docs
```
=> chore(PA): Remove `Xandra.Cluster` from supervision tree

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_events_producer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/control_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/data_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/telemetry.ex
- Add new telemetry metrics `ControlHandler`, `DataHandler`, and `AMQPEvents`
- Expand `published_events` counter to not only count events but also track the event type
```docs
```
=> refactor(DUP): Expand metrics

apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/room.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/telemetry.ex
Expanded metrics with:
- count of watch requests
- count of unwatch requests
- total bytes retrieved per interface
```docs
```
=> refactor(AEA): expand metrics

.github/workflows/astarte-end-to-end-test-workflow.yaml
Introduce caching of the docker builds for end-to-end testing
Speeds up CI times
Fixes #
```docs
```
=> ci: e2e caching

apps/astarte_housekeeping/lib/astarte_housekeeping/config.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/config/telemetry_type.ex, apps/astarte_housekeeping/lib/astarte_housekeeping_web/telemetry.ex, apps/astarte_housekeeping/lib/astarte_housekeeping_web/telemetry/database_events.ex
Adds support for xandra telemetry events, to give visibility over query exceptions and failures.
=> feat(housekeeping): support xandra telemetry events boungcing

apps/astarte_trigger_engine/lib/astarte_trigger_engine/config.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/config/telemetry_type.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/telemetry.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/telemetry/database_events.ex
Bounces xandra telemetry events as `astarte.trigger_engine.database` events to give visibility over query failures and exceptions
=> feat(te): support xandra telemetry events

tools/astarte_e2e/lib/astarte_e2e/application.ex, tools/astarte_e2e/lib/astarte_e2e/data_trigger.ex, tools/astarte_e2e/lib/astarte_e2e/device_trigger.ex, tools/astarte_e2e/lib/astarte_e2e/task_scheduler.ex, tools/astarte_e2e/lib/astarte_e2e_web/router.ex, tools/astarte_e2e/lib/astarte_e2e_web/trigger_controller.ex
verify the e2e test receives http device triggers from astarte
=> feat(e2e): device trigger round trip

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex
Report the changes occurred in the release-1.3 branch regarding configurations and environment variables.
Report the changes occurred in the release-1.3 branch regarding configurations and environment variables.
=> docs: update changelog with configuration and env var changes

tools/astarte_e2e/lib/astarte_e2e/amqp_device_trigger.ex
amqp device trigger roundtrip
Fixes #
```docs
```
=> feat(e2e): amqp device trigger roundtrip

apps/astarte_pairing/config/dev.exs, apps/astarte_pairing/config/prod.exs, apps/astarte_pairing/config/test.exs, apps/astarte_pairing/lib/astarte_pairing/cfssl_credentials.ex
Security event: generate a log upon successful csr signing.
Fixes #
=> chore(pairing): generate a log before returning cert_data 

apps/astarte_pairing/lib/astarte_pairing/cfssl_credentials.ex
=> chore(pairing): add logs when issuing a certificate fails
