generate-compose-files.sh
The script was still checking for the old generated files so it
regenerated keys every time
=> generate-compose-files: check the right files for existence

docker-compose.yml
i.e. the two that must wait for deps (wait-for is not very robust)
=> docker-compose.yml: restart services that may fail

compose/astarte-dashboard/config.json, doc/pages/tutorials/010-astarte_in_5_minutes.md, docker-compose.yml
This PR adds Astarte Dashboard to our default Docker Compose installation, in a dedicated container.
=> Add Dashboard to Docker Compose

doc/pages/architecture/080-mqtt-v1-protocol.md
Timestamp type was wrong  for the first BSON hexdump. The example had int64, but the timestamp must be a datetime (0x09).
=> 080-mqtt-v1-protocol.md: fix a hexdump

docker-compose.yml
master docker-compose.yml should pull grafana and vernemq snapshots
instad of 0.10-snapshot.
=> docker-compose.yml: use vernemq and grafana snapshot in master

CHANGELOG.md, docker-compose.yml
If this isn't done and no external CA is set, everytime cfssl restarts a new CA will be created, invalidating all existing device certificates and causing inevitable flooding in Pairing.
Fixes #55
=> docker-compose: Persist CFSSL storage

doc/pages/tutorials/010-astarte_in_5_minutes.md
Use openssl everywhere to avoid incompatibilities with ssh-keygen's key format on some platforms.
Fixes #63
=> Deprecate ssh-keygen

doc/pages/architecture/030-interface.md
The following enpoints:
some/%{param}
/some/thing/value
are overlapping since Astarte doesn't allow an endpoint that is a prefix of
another one to be in the same interface, as it is reserved to be used to
retrieve the endpoints collection (e.g. `/some/thing` and `/some/thing/here`
are overlapping).
=> Add one more overlapping endpoints example

docker-compose.yml
VerneMQ docker image had a bug and a new release candidate has been released.
=> docker-compose.yml: switch vernemq to 0.10.0-rc.1

README.md
release-0.10 branch README.md should tell users to clone release-0.10
branch.
=> README: add -b release-0.10 to git clone command

Dockerfile, docker-compose.yml
0.10.1 release has been tagged, now Dockerfile and docker-compose.yml
can be switched back to release-0.10 branch/0.10-snapshot builds.
=> Dockerfile/docker-compose.yml: switch back to 0.10-snapshot

doc/pages/administrator/050-installation_standalone.md
Installation with Standalone components is not supported right now, so
remove it from documentation.
Signed-off-by: Davide Bettio <davide.bettio@ispirata.com>
=> doc: remove "Installation with Standalone components" page

.github/labeler.yml, .github/workflows/pr-labels.yaml
Set up standard GitHub Actions workflow for labeling PRs automatically based on Paths.
=> workflows: Add Labeler

.github/workflows/pr-labels.yaml
Due to the secrets.GITHUB_TOKEN current fiasco, on: [pull_request] doesn't cut it.
Switch to cron until there is a solution to this.
=> workflows: Fix labeler workflow

apps/astarte_housekeeping/lib/astarte_housekeeping/migrator.ex
set_schema_version returns atom errors, handle them without crashing
=> migrator: handle {:error, reason} in execute_migrations

generate-compose-files.sh
Leftover from key generation rework
=> generate-compose-files: use astartectl key filename

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/mix.lock, apps/astarte_data_updater_plant/test/support/database_test_helper.exs, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/mix.lock, apps/astarte_realm_management/test/support/database_test_helper.exs, apps/astarte_realm_management_api/mix.lock
Allow to configure a per mapping database retention policy and ttl.
Fix  #136
=> Add support for mapping database retention policy and ttl

doc/mix.exs
By default ex_doc generates a "API refenrece" page. This will remove it and its relative entry from the sidebar menu
=> mix.exs: disable autogenerated API page

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs, apps/astarte_data_updater_plant/test/support/database_test_helper.exs
Load triggers targeting interface `*`, while limiting them to `incoming_data` triggers.
=> Fix any_interface triggers

doc/pages/tutorials/010-astarte_in_5_minutes.md
We are now using ScyllaDB with docker-compose, update the
tutorial accordingly.
=> 010-astarte_in_5_minutes: Replace Cassandra with ScyllaDB

doc/pages/architecture/060-triggers.md, doc/pages/tutorials/010-astarte_in_5_minutes.md, doc/pages/user/052-using_channels.md, doc/pages/user/060-using_triggers.md
stream-qt5-test doesn't use anymore org.astarteplatform.Values, use
org.astarte-platform.genericsensors.Values everywhere instead.
=> doc: use org.astarte-platform.genericsensors.Values

standard-interfaces/org.astarte-platform.genericsensors.Values.json
Set org.astarte-platform.genericsensors.Values.json/%{sensor_id}/value
explicit_timestamp to true.
=> standard-interfaces: add missing explicit_timestamp

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
Use realm wide or interface TTL while inserting values into the database. Fix #239
=> Handle TTL for server owned interfaces

apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
database_retention_policy/ttl were missing in fetch_interface.
=> Queries: fix: add missing database_retention_policy/ttl

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/pr-container-build-workflow.yaml
All Astarte apps should be tested regardless of failed tests.
=> workflows: disable fail-fast

apps/astarte_appengine_api/test/astarte_appengine_api_web/channels/rooms_channel_test.exs
The test was sometimes failing due to a missing Mox stub. Fix this.
=> rooms_channel_test: add stub to test

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Ensure validate_value function discard any (map, not_map) or (not_map,
map) pair, otherwise Map.fetch would crash.
=> DUP: an unexpected object aggregated value was crashing DUP

CHANGELOG.md
Keep a changelog recommends dividing changelog entries into Added,
Changed and Fixed.
=> CHANGELOG.md: divide 0.11.0-rc.0 entries to Added/Changed

apps/astarte_appengine_api/mix.exs, apps/astarte_appengine_api/mix.lock, apps/astarte_data_updater_plant/mix.exs, apps/astarte_data_updater_plant/mix.lock, apps/astarte_pairing/mix.exs, apps/astarte_pairing/mix.lock, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management/mix.lock, apps/astarte_trigger_engine/mix.exs, apps/astarte_trigger_engine/mix.lock
Fix a problem preventing re2_nif.so from being compiled and consequently
blocking all applications from starting up
=> Force update of :re2 in all apps that have it as a dependency

.github/workflows/astarte-apps-build-workflow.yaml
Caching in our current actions workflows had three big issues:
1. Caching was done regardless of the Elixir/OTP version
2. Caches were potentially shared across dialyzer and build
3. Caches were potentially shared across different apps
This resulted in all sorts of flakes and incompatibilities across different release branches. This PR implements a way stricter approach to caching which should hopefully address all of these issues.
=> actions: Fix a number of issues related to caching

apps/astarte_appengine_api/mix.exs, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_pairing/mix.exs, apps/astarte_realm_management/mix.exs, apps/astarte_trigger_engine/mix.exs
Temporary work around since astarte_data_access will be updated in the
Skogsra PR (#274) since its API changed
=> Temporarily force re2 to version 1.9.4 in all apps

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
CQEx does not support passing a DateTime as timestamp value in a query, fix that
=> appengine_api: convert DateTime values to millisecond epoch

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Fix a bug that was preventing volatile triggers (specifically, the ones
targeting the * interface) to be loaded immediately.
Fix #300
=> data_updater_plant: always immediately load triggers on success

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
The trigger has to be loaded only when it targets the `*` interface. In all
other cases the interface is not yet loaded, so the trigger will be loaded as
soon as the device sends data on it.
Fixup for PR #301.
=> data_updater_plant: fix previous PR (#301)

CHANGELOG.md, apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex, apps/astarte_housekeeping/test/astarte_housekeeping/queries_test.exs
This is a work-around for https://github.com/lexhide/xandra/issues/179 to avoid
that the public key of a newly created realm gets written to another one.
Fix #294
=> housekeeping: use explicit keyspace in queries when creating a realm

apps/astarte_appengine_api/config/config.exs, apps/astarte_appengine_api/lib/astarte_appengine_api_web/metrics/pipeline_instrumenter.ex, apps/astarte_housekeeping_api/config/config.exs, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/metrics/pipeline_instrumenter.ex, apps/astarte_pairing_api/config/config.exs, apps/astarte_pairing_api/lib/astarte_pairing_api_web/metrics/pipeline_instrumenter.ex, apps/astarte_realm_management_api/config/config.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/metrics/pipeline_instrumenter.ex
Limit the number of different metrics which are generated. In particular, don't split metrics based on request_path`. See Issue #339
=> Fix exposed metrics

apps/astarte_appengine_api/lib/astarte_appengine_api_web/endpoint.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/config.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/config.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/endpoint.ex, apps/astarte_pairing/lib/astarte_pairing/config.ex, apps/astarte_pairing_api/lib/astarte_pairing_api/config.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/endpoint.ex, apps/astarte_realm_management/lib/astarte_realm_management/config.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/config.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/endpoint.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/config.ex
+ Allow to configure the ports for each service
+ All the services with an API allow the port configuration in a single point (i.e. releases.exs)
+ Adopt a coherent naming for port env (i.e. <SERVICE_NAME>_PORT)
=> Make ports configurable for each service

apps/astarte_appengine_api/lib/astarte_appengine_api/config.ex
Remove enable compression env var as it is not used by Phoenix.
=> Remove enable compression from appengine env vars

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/metrics/appengine_instrumenter.ex
=> appengine_instrumenter: use Counter.inc with :discarded_events_total

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/server.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/message_tracker.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/message_tracker/server.ex
Make a Data Updater deactivate if it doesn't receive any message for 3 times the
device heartbeat interval.
Fix #354
=> data_updater_plant: add Data Updater deactivation

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/fallback_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/error_view.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs
+ Do not crash when using an empty string for aliases (either key or
value). 400 is returned instead.
+ Do not crash when using an empty string for metadata keyi. 400 is
returned instead.
+ Metadata values can be set to empty string.
Fix #357
=> appengine_api: prevent crashes when updating metadata or aliases

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Avoid crashes in the database due to passing around invalid strings.
Fix #371
=> data_updater: check if path and interface are valid UTF-8 strings

doc/pages/architecture/030-interface.md
=> 030-interface: update documentation to reflect actual data type limits

CHANGELOG.md, apps/astarte_data_updater_plant/config/astarte_data_updater_plant.schema.exs, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer/supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/consumers_supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater.ex
Avoid stalling a Data Updater when it is started through an RPC call instead of
being started by AMQPDataConsumer.
Fix #375
=> data_updater: serialize MessageTracker and DataUpdater.Server starts

CHANGELOG.md, apps/astarte_trigger_engine/config/astarte_trigger_engine.schema.exs, apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_events_consumer.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/config.ex
Avoid excessive memory usage when consuming events
=> trigger_engine: add AMQP prefetch count

compose/astarte-dashboard/config.json
=> compose: remove /v1 prefix from dashboard configuration

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/config.ex
The erlang default of 1 is too strict. Increase the default value to 10
to make it coincident to OpenSSL default.
=> Default max certificate chain length to 10

doc/pages/architecture/060-triggers.md
AMQP 0-9-1 actions had few typos, fix them.
=> doc: fix typos in 060-triggers.md

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/data_transmitter.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rpc/vmq_plugin.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/fallback_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/error_view.ex, apps/astarte_appengine_api/mix.lock, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/vmq_plugin.ex, apps/astarte_data_updater_plant/mix.lock
Use the number of local and remote returned by `astarte_vmq_plugin` (see https://github.com/astarte-platform/astarte_vmq_plugin/pull/25) to determine if a publish has reached the required level of consistency, based on the requested QoS.
=> Handle publish reply and ensure publishes towards the device

doc/swagger-ui-index.html
doc/swagger-ui-index.html was pointing to release-0.10 yaml file on v0.11
branch.
=> doc/swagger-ui-index.html: use v0.11 AppEngine API swagger

doc/swagger-ui-index.html
Use URL to master yamls instead of release-0.11 ones.
=> doc/swagger-ui-index.html: use snapshot API instead of 0.11 one.

apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_events_consumer.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/config.ex
Allow the setting of amqp_prefetch_count for trigger engine. Avoid
excessive memory usage when consuming events.
Fix #404
=> trigger_engine: add amqp_prefetch_count on 1.0 too

apps/astarte_appengine_api/Dockerfile, apps/astarte_data_updater_plant/Dockerfile, apps/astarte_housekeeping/Dockerfile, apps/astarte_housekeeping_api/Dockerfile, apps/astarte_pairing/Dockerfile, apps/astarte_pairing_api/Dockerfile, apps/astarte_realm_management/Dockerfile, apps/astarte_realm_management_api/Dockerfile, apps/astarte_trigger_engine/Dockerfile, tools/astarte_export/Dockerfile, tools/astarte_import/Dockerfile
There is no "official" OTP23 + Elixir 1.10.3 image, so use a custom one.
=> Use Ispirata OTP23 + Elixir 1.10.3 docker image

CHANGELOG.md, apps/astarte_appengine_api/mix.lock, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/triggers_handler.ex, apps/astarte_data_updater_plant/mix.lock, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/triggers_handler_test.exs, apps/astarte_trigger_engine/mix.lock, doc/pages/architecture/060-triggers.md, doc/pages/user/045-device_errors.md, doc/pages/user/052-using_channels.md
DeviceErrorEvent is now emitted when a device_trigger on device_error is
installed, either with RealmManagement or through a volatile AppEngine trigger.
Fix #135
=> Add device error triggers

CHANGELOG.md, apps/astarte_appengine_api/config/config.exs
It was false before the switch from Conform to Skogsra and leaving it at
its default value breaks the dashboard
=> astarte_appengine_api: bring check_origin back to false

apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/http_action.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/http_action_test.exs, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex, doc/pages/architecture/060-triggers.md
http_static_headers is consistent with AMQP amqp_static_headers and also
it underlines that they are just a subset of all http headers.
"http_custom_headers" has not been chosen since they might be also standard/well-know
headers, such as Authorization.
Furthermore an additional test has been added for http action Jason
encoder.
=> Rename http_(custom)_headers to http_static_headers

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
Match on lists of all lengths, not just 2
=> appengine: fix extract_aggregate_reliability pattern match

CHANGELOG.md, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/realm.ex, apps/astarte_housekeeping_api/test/astarte_housekeeping_api/realms/realms_test.exs
The backend already checks that the datacenter is the one contained in the
database, and it's used in a prepared query (so it can't be used as vector for
SQL injections). We can't predict datacenter names, so we might as well drop the
check.
=> housekeeping_api: remove datacenter name regex check

apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex
It was checked a second time in the backend. See
9af8f9f09bb524afd9ce10431665e877635da748.
=> housekeeping: remove datacenter regex check

apps/astarte_appengine_api/lib/astarte_appengine_api/health.ex
Health status queries were failing because of local_quorum consistency
level: replace it with quorum.
=> appengine_api: s/local_quorum/quorum/g

CHANGELOG.md, apps/astarte_housekeeping/lib/astarte_housekeeping/release_tasks.ex
Increase the delay between connection attempts towards Cassandra to 1000
ms, for an overall number of 60 attempts.
Fix #427
=> housekeeping: increase the delay between connection attempts

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
A push can fail only if the device doesn't have a session on the broker. But if
it this happen, then the device will ask for all properties at the next
reconnection. This allows to push properties to devices before their first
connection, making sure they're saved to the database.
=> appengine_api: always consider push to properties interfaces succesful

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex
Exploit astarte's mulitique support by default.
=> data_updater_plant: default data queue count to 128

CHANGELOG.md, apps/astarte_appengine_api/config/config.exs
Remove `topic` from channel metrics preventing the unbounded growth of
metrics' entries.
=> appengine_api: remove `topic` from channel metrics

CHANGELOG.md, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex, doc/pages/architecture/060-triggers.md
Allow the user to make the requests go through even if an invalid certificate is
involved.
=> Add ignore_ssl_errors option to trigger action

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex
Also give them a default value, since using nil results in a trigger
installation failure
=> realm_management: static_headers need to be passed as list

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Mark device as offline and send device_disconnected event when forcing a device disconnection
Fix #398
=> Handle device disconnection

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/vmq_plugin.ex
The return value of ask_clean_session was ignored before, so it did not crash
the process. 5beed84913138bb5ecaa902b1bb64435b191df14 introduced the use of the
returned value, so the process now crashes if an error is returned, which was
happening when we tried to disconnect a device that was already disconnected.
This fixes that problem, making sure to return :ok in that case.
=> data_updater_plant: fix queue block during ask_clean_session

CHANGELOG.md, docker-compose.yml
The short syntax for docker-compose volumes creates the source on the
host if it does not exist. This meant that user that accidentally tried
to launch docker-compose up before executing docker-compose-initializer
found themselves with a housekeeping_public.pem directory, that was seen
as an existing file by the initializer and left the setup in an invalid
state.
Using the long syntax avoids the silent creation of the directory and
just makes the docker-compose up command fail (so the user can read the
instructions again and find docker-compose-initializer).
The long volume syntax requires at least compose syntax v2.3, so we also
have to bump that.
=> docker-compose: avoid accidentally creating housekeeping_public.pem

CHANGELOG.md, compose/cfssl-config/db_config.json, docker-compose.yml
We already removed the dependency from K8s deployments, it makes sense to also
do this in this kind of setup.
=> docker-compose: make CFSSL stateless, removing postgresql dependency

standard-interfaces/org.astarte-platform.genericcommands.ServerCommands.json, standard-interfaces/org.astarte-platform.genericevents.DeviceEvents.json
Allow sending generic events and commands
=> Add ServerCommands and DeviceEvents standard interfaces

tools/astarte_e2e/lib/astarte_e2e/config.ex
If astarte_e2e is launched in a container, the hardcoded path to priv is
not working. Overcome this limitation using `:code.priv_dir/1`.
=> Let astarte_e2e find priv directory

apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml
=> astarte_pairing_api: don't use legacy format for hw_id

.github/workflows/astarte-end-to-end-test-workflow.yaml, docker-compose.yml
This also has the nice side effect of adding the ability of locally testing astarte with docker-compose, building it from the repository.
=> Add E2E CI

tools/astarte_e2e/config/prod.exs, tools/astarte_e2e/lib/astarte_e2e/service_notifier.ex
+ debug messages are ignored in prod env
+ decouple deliver/1 from specific log messages
=> Improve logs

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/docs-workflow.yaml
This is needed since Github deprecated some commands that were used by the old
version, see
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Update setup-elixir Github action

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
database_retention_ttl was ignored on device-owned interfaces with object
aggregation, fix that.
Fix #501
=> data_updater_plant: use database_retention_ttl in device aggregates

compose/astarte-dashboard/config.json
Don't show Flow related stuff on the Dashboard
when using docker-compose, as Flow is not deployed
Signed-off-by: Mattia Pavinati <mattia.pavinati@ispirata.com>
=> Disable flow preview in local dashboard

doc/pages/administrator/010-system_requirements.md, doc/pages/administrator/020-prerequisites.md
cert-manager is a new needed dependency for Astarte Operator 1.0+ that has to be manually installed for a number of good reasons. Detail in the docs how to proceed and how to set up the Cluster.
=> docs: Add needed steps to install cert-manager

doc/mix.exs
This enables the version-selection dropbox in the documentation's website, making it future-proof from here on.
=> doc: Add javascript_config_path to doc configuration

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, doc/pages/architecture/060-triggers.md
value_change, value_change_applied and path_removed work only with
properties interfaces.
Make sure this contraint is validated in realm management and document
it.
See also issue #507.
=> value_change* and path_removed are valid only with properties interfaces

README.md
tag was missing in example git clone.
=> README.md: add missing -b 0.11.4

doc/pages/architecture/070-auth.md, doc/pages/user/040-connect_device.md
This MR replaces broken links in the documentation that resulted in 404 pages with up-to-date links.
=> Fix broken links in documentation

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
The call to retrieve_endpoint_values was discarding opts when multiple paths
were present in an object aggregation (e.g. when it contained multiple instances
of a parametric path). This caused the call to always have false in the
explicit_timestamp option, which in turn caused a crash when an interface with
explicit_timestamp true was queried due to different timestamp columns.
Fix #480
=> device: don't discard opts when retrieving object aggregations

doc/pages/tutorials/010-astarte_in_5_minutes.md
Scylla requires /proc/sys/fs/aio-max-nr to be at least 1048576
See also https://github.com/scylladb/scylla/issues/5638
Signed-off-by: Mattia <mattia.pavinati@ispirata.com>
=> Add requirements for scylla db docker image

doc/pages/upgrade/020-upgrade_011_10.md
Users should be aware of the dangling CSFFL pv after upgrading to 1.0. Make it clear adding a small section to the docs.
=> Update docs to warn about dangling CFSSL pv after upgrading to 1.0

doc/pages/tutorials/010-astarte_in_5_minutes.md
Fix Astarte in 5 minutes guide where the astartectl command to create a realm used a not existent flag.
=> Docs: fix astartectl command to create a realm

doc/pages/tutorials/010-astarte_in_5_minutes.md
Fix typo in Astarte in 5 minutes guide where there was a reference to a non existent URL.
=> Docs: fix Astarte in 5 minutes typo for Trigger example

doc/pages/architecture/090-database.md
This way the old column is still there while the new one can be already used,
and a migration procedure can be easily implemented if needed
=> 090-database: invert manual migration steps for attributes column

CHANGELOG.md, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/amqp_action.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/amqp_action_test.ex, doc/pages/architecture/060-triggers.md
An empty routing key is problematic since it's not possible to easily bind an
Exchange and a Queue with an empty routing key. Hence, we make it mandatory to
provide a routing key to make the bind explicit.
=> amqp_action: make amqp_routing_key mandatory

doc/pages/upgrade/020-upgrade_011_10.md
Add caveat for 0.11 -> 1.0 migration docs to advise users to use the new Astarte Channels endpoint since the already deprecated `/socket` route on AppEngine has been definitely removed in v1.0 in favor of `/v1/socket`
=> Add note on /socket endpoint deprecation for Astarte Channels

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/astarte_value.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/astarte_value_test.exs
The interaction between https://github.com/astarte-platform/astarte/issues/550
and https://github.com/astarte-platform/astarte/pull/551 was preventing
aggregate interfaces that got populated with incomplete objects to be queried.
This fixes that, allowing AppEngine to return null in some JSON fields (since
it's not its job to fix that kind of issue anyway).
=> appengine: allow returning nil in AstarteValue.to_json_friendly

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Remove `aggregation query without partition key` Cassandra warning when checking Astarte's health.
See #420.
=> Fix Cassandra warning in Realm Management logs

doc/pages/architecture/030-interface.md
Additional properties can be set only at mapping level.
=> Fix docs on datastream-specific features of interfaces

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
The query was limiting the delete operation on all interfaces with given
name. The DELETE query must be limited using (name, major) couple,
otherwise other interfaces are deleted by mistake.
This bug was not causing data loss, however it causes service
distruption and it requires a manual fix.
=> RM: Queries: fix all interfaces with same name deletion bug

doc/pages/upgrade/020-upgrade_011_10.md
`awk` is breaking the upgrade procedure for OSX users. Use `gawk` to ensure the proper behavior.
Fix  #593
=> 020-upgrade_011_10: make clear we need `gawk`

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
This reverts commit 974c065bc937c683c32691ea90ba620984fd39f2.
Volatile triggers are now supported even in object aggregation since all
types are correctly JSON encoded even if they're contained in an object
aggregation (see
https://github.com/astarte-platform/astarte_core/commit/b22148daf84cf2355e9e7ba02e9ce39dae5db336)
=> Revert "DataUpdater: triggers are not yet supported on object aggregated

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/triggers_handler.ex
Maximum (exponential) backoff time is now around 5 minutes.
=> Data Updater Plant: use a reasonable backoff time when publishing to RabbitMQ.

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/astarte_value.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/astarte_value_test.exs
This is needed to handle object aggregations with missing endpoints, which are
supported due to interface versioning. This avoid crashes when nil values are
received on mappings with datatypes which imply a conversion.
=> appengine: fix null values support in interfaces

docker-compose.yml
Make sure that all images are always tagged / versioned.
=> compose: Always pull CFSSL 1.4.1-astarte.0 for 0.11

doc/pages/administrator/095-advanced-operations.md, doc/pages/upgrade/020-upgrade_011_10.md, doc/pages/upgrade/030-upgrade_10.md
The stable Operator's Helm chart was released. Using `--devel` is not
needed anymore. Thus, remove it from the instructions contained in the
doc.
=> Remove leftover `--devel` from the docs

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/config/non_negative_integer.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
When querying on an interface for device data with `since`, `to` and `sinceAfter` params, Appengine API does not fail if the result is empty. See [#552](https://github.com/astarte-platform/astarte/issues/552).
=> Fix 500 error in Appengine when interface queries have no matching data

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex
Those properties are purely device side so they should not be considered
breaking when updating an interface to a different minor version
Signed-off-by: Riccardo Binetti <riccardo.binetti@secomind.com>
=> realm_management: allow retention and expiry changes in minor update

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
Do not crash when datetimearray values are pushed to Astarte on a server-owned interface.
Apply the fix in #610 to AppEngine, too.
=> AppEngine: Fix reception of server-owned datetimearray values

CHANGELOG.md, apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/fallback_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/error_view.ex, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml
Add a check on the presence of active devices when realm deletion is performed, in order to avoid unexpected device behaviour. The async API still returns a success.
See #661.
=> Housekeeping: do not delete realm having connected devices

CHANGELOG.md, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/realms.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/realm_controller.ex, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml
Allow user to create/delete realms with synchronous calls using the `async_operation` query param. Default to the current behaviour, i.e. async calls.
=> Housekeeping API: add synchronous API for realm operations

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/interfaces.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_controller.ex, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs
Allow user to create, delete or update interfaces in a synchronous fashion using the `async_operation` query param. Default to the current behaviour, i.e. async calls.
=> Realm Management API: add synchronous API for interface operations

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Also, fix a small typo in the log tag.
Closes #663.
=> DUP: log the key when `unexpected_object_key` occurs

apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml
As you can see `created` [status](https://hexdocs.pm/plug/Plug.Conn.Status.html#code/1-known-status-codes) is returned on successful realm creation (https://github.com/astarte-platform/astarte/blob/release-1.0/apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/realm_controller.ex#L43)
=> openapi: Fix HTTP response code on realm creation

.github/workflows/docs-workflow.yaml
Restore the `astarte-kubernetes-operator` subdirectory, too.
=> Do not remove operator docs in docs workflow

apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml
As you can see no_content [status](https://hexdocs.pm/plug/Plug.Conn.Status.html#code/1-known-status-codes) is returned on successful [delete](https://github.com/astarte-platform/astarte/blob/release-1.0/apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/interface_values_controller.ex#L92)
=> OpenAPI: Fix HTTP response code for delete on device interface endpoint

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
Take into account the `allow_bigintegers` and `allow_safe_bigintegers` options when querying the root of individual datastream or properties interfaces. Keep the behaviour as default in order not to break the API.
Close #630 .
=> AppEngine: return longinteger values as string for some interface combinations

CHANGELOG.md, doc/pages/administrator/020-prerequisites.md, doc/pages/administrator/050-handling_certificates.md, doc/pages/upgrade/020-upgrade_011_10.md
cert-manager 1.1.0 is quite old and is not supported anymore on k8s 1.22+. Thus, bump the dependency for Astarte.
=> Doc: bump cert-manager version to 1.7.0

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_events_producer.ex
Under heavy loads, the declare exchange call might fail because of the low value of the default timeout. Thus, increase that value to 60 seconds.
=> Data Updater Plant: increase timeout for declare_exchange

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_events_producer.ex
Under heavy loads, the publish call might fail because of the low value of the default timeout. Thus, increase that value to 60 seconds.
=> Data Updater Plant: increase timeout for AMQPEventsProducer publish

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/fallback_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/error_view.ex, apps/astarte_appengine_api/test/astarte_appengine_api_web/views/error_view_test.exs
Instead of failing, return a 405 Method Not Allowed error if:
- A client tries to publish data on a device-owned interface;
- A client tries to publish data on an incomplete path of a server-owned interface.
Close #264 .
=> AppEngine: do not crash on some malformed POST/PUT requests 

doc/pages/administrator/020-prerequisites.md, doc/pages/administrator/064-setup_astartedefaultingress.md, doc/pages/administrator/066-migrate_to_astartedefaultingress.md, doc/pages/administrator/095-advanced-operations.md, doc/pages/upgrade/030-upgrade_100_10x.md
- Document how to migrate from the deprecated AstarteVoyagerIngress to the new AstarteDefaultIngress;
- Rework the upgrade guide v1.0.0 --> v1.0.x to avoid duplicate information;
- Add the AstarteDefaultIngress resource to the backup and restore procedures.
=> Document the procedure to migrate to the AstarteDefaultIngress

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/trigger_view.ex, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml
- RealmManagement API does not crash on trigger errors and produces informative responses
- RealmManagement logs trigger retrieval / deletion errors
Fix #683.
=> RealmManagement / API: handle gracefully all trigger errors

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
When unsetting properties, do not check if the device has a session on the broker and return a success.
Indeed, the device will receive the unset information anyway (either when it reconnects or in the
`/control/consumerProperties` message).
Closes #640 .
=> Appengine API: always consider properties unset succesful

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
A successful server-side property unset made the controller fail because no clause matched the result.
Fix this by providing a meaningful return value when unsetting the property.
=> AppEngine: do not fail on successful server-side property unset

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Log the base64-encoded payload instead of the Elixir binary representation.
=> DUP: better logs on receving unexpected object key

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/room.ex, apps/astarte_appengine_api/test/astarte_appengine_api_web/channels/rooms_channel_test.exs, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs
Volatile triggers are currently installed even if they refer to a device that does not exist; this causes 
1. DataUpdaterPlant to fail to initialise the data updater process for such device
2. the AppEngine RPC to DataUpdaterPlant to timeout.
Check that the relevant device exists before allowing volatile triggers.
=> Volatile triggers: do not install if target device does not exist

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/event_type_utils.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/triggers_handler.ex, apps/astarte_data_updater_plant/mix.lock, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs, apps/astarte_realm_management/mix.lock, apps/astarte_realm_management_api/mix.lock
Allow to create device triggers which refer to device introspection, such as:
- incoming introspection, when device introspection is received, e.g.
```json
{
"name": "incoming_introspection_trigger",
"action": {
"http_url": "https://4yagof76fkbopbuc.mfpb.in",
"http_method": "post"
},
"simple_triggers": [
{
"type": "device_trigger",
"on": "incoming_introspection",
"device_id": "HEbrzh3hSx2k_NfgyK24yw"
}
]
}
```
- interface added, when a new interface is added to introspection;
- interface minor updated, when an interface gets a minor bump, e.g.
```json
{
"name": "interface_minor_updated_trigger",
"action": {
"http_url": "https://mkupllkgyacgjnal.mfpb.in",
"http_method": "post"
},
"simple_triggers": [
{
"type": "device_trigger",
"on": "interface_minor_updated",
"interface_name": …
```
=> Support introspection triggers

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs
Fix [531](https://github.com/astarte-platform/astarte/issues/531).
=> AppEngine: Intermediate paths return valid data also when a `properties` interface is not fully populated

CHANGELOG.md, README.md, apps/astarte_trigger_engine/mix.lock, doc/pages/tutorials/010-astarte_in_5_minutes.md
[#737](https://github.com/astarte-platform/astarte/pull/737/) did not include some changes from release-1.0, i.e. 1.0.4 CHANGELOG.md entry, documentation bits, minor dep update in TriggerEngine.
Add them.
(version control works in mysterious ways)
=> Include changes from release-1.0

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
`binaryblob` and `datetime` (and their array equivalents) were not handled correctly in server owned aggregated interfaces (see linked issues below), this PR fixes the bug.
Additionally, it fixes a crash (discovered while testing) that happened when sending non-array values on array endpoints.
Fix #753
Fix #754
=> Handle `binaryblob` and `datetime` in server aggregates

apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/action.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/http_action.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/http_action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/trigger_test.exs
Add `ignore_ssl_errors` to HttpAction and Action schemas. Default the field value to false.
Closes #756.
=> RM API: consider the ignore_ssl_errors field in Actions

doc/pages/user/062-using_trigger_delivery_policies.md
An example of Trigger Delivery Policy is referring to a *none* strategy that does not exist.
The PR fixes the example so that existing strategies are used.
=> Fix docs example of Trigger Delivery Policy using undefined strategy

apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml
Renamed handler field name to an "error_handlers" in the Realm Management API yaml file.
Closes #762
=> RM API doc: update handler field name in Trigger Delivery Policy

doc/pages/administrator/095-advanced-operations.md
Not every section of the advanced operations belong to the Astarte operator. 
Then, restore the relevant parts for Astarte. 
This partially reverts commit 9d737daf8a251286c9e1cbf1cb666d8c49b04219.
Fix #773
=> Restore the "advanced operations" section for Astarte

apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_policy_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/trigger_policy_view.ex
Display incorrect and excessive parameters solved by excluded ```"keyword"``` and ```"error_codes"``` from ```"error_handlers"``` field to get correctly-formatted Trigger Policy.
Modified ```trigger_policy_view.ex``` and added ```keys: :atoms!``` option in ```trigger_policy_controller.ex``` to use (safe) atoms as keys to simplify handler normalization in Trigger Policy View.
Fix #766.
=> RM API: Return a correctly-formatted Trigger Delivery Policy

compose.env, compose/astarte-dashboard/config.json, docker-compose.yml
Expose Astarte with Traefik. Use the following URL scheme:
- API: `http://api.astarte.localhost/<service name>`
- Broker: `mqtts://broker.astarte.localhost`
- Dashboard: `http://dashboard.astarte.localhost`
The old URLs (e.g. `http://localhost:4002`) will not work anymore.
Contextually, give an explicit name to the docker network used by services.
Close #761.
=> docker-compose: use a standard URL scheme

doc/pages/architecture/030-interface.md
Restore the limitations section within the interfaces page. The section was erroneously removed in the context of 4479a38.
Contextually, additional limitations on the endpoints naming are added.
=> [Doc] Restore limitations section for interfaces

doc/pages/tutorials/010-astarte_in_5_minutes.md, doc/pages/user/015-astarte_dashboard.md, doc/pages/user/080-grafana_datasource.md
Use the addresses exposed by Traefik rather than clunky ports.
=> Doc: use new URLs in "Astarte in 5 minutes"

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/server.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs
Support the new `internal` message type (see https://github.com/astarte-platform/astarte_vmq_plugin/pull/71). For now, only the device heartbeat message is internal. Support the old heartbeat type, too, for the time being.
=> DUP: Use the `internal` event type for Astarte internal messages (e.g. device heartbeat).

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
The `version` field was deprecated since 1.1.0-rc.0 (see https://github.com/astarte-platform/astarte_core/pull/82/commits/6b397be7bef6f7e44ca37c1750cf2ca1e446e7c7). Do not fail when decoding an event proto that does not contain that field.
=> TriggerEngine: do not fail when receiving events with `version` unset

.github/workflows/docs-workflow.yaml, doc/mix.exs
Time to move to a newer version of Elixir (i.e. 1.14) for the documentation project.
Contextually, bump versions in docs-workflow.
=> Doc: bump Elixir version

docker-compose.yml
bump to latest available version.
minimum docker engine version is 19.03.0, which also happens to be the recommended version for astarte 1.1
=> chore(docker-compose): bump version 2.3 -> 3.8

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
Return the number of results specified by `downsample_to` when:
- there are more samples than the default query limit.
- `format=disjoint_tables` is used.
This is obtained by checking that the actual result size is taken into consideration when downsampling.
Note that if `downsample_to` > query limit, result may still not be accurate.
Fixes #149 and #824.
=> AppEngine: match number of returned result with downsample_to in corner cases

.github/workflows/astarte-end-to-end-test-workflow.yaml
Update astartectl and wait-for-astarte-docker-compose in order to enable e2e tests to safely run again.
=> CI: update tools in E2E workflow

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/queries.ex
modify the health check to use queries which do not generate warnings from cassandra.
akin to https://github.com/astarte-platform/astarte/pull/571.
closes #817.
=> fix(appengine): remove cassandra warnings

CHANGELOG.md, apps/astarte_pairing/lib/astarte_pairing/config.ex
fix the typo trying to match `ca_cert`, which lead to a crash in the case a custom certificate was given.
=> fix(pairing): don't crash with custom CA certificate

doc/pages/tutorials/010-astarte_in_5_minutes.md
Ensure that v1.1.0 is checked out.
=> Astarte in 5 minutes: use v1.1.0

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/server.ex
This feature could cause more harm than good, since DataUpdater was actually totally unmonitored and unlinked between its start and when the :initialize info was handled, which could lead to undetected crashes.
=> data_updater: remove async startup

doc/pages/architecture/040-interface_schema.md
=> Move `explicit_timestamp` to mapping section.

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
Binaryblobarrays were not wrapped to the appropriate bson structure. 
Fix it, allowing to send binaryblobarrays on server owned interfaces.
=> Appengine: properly wrap binaryblobarray to bson

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex
Successful synchronous operations (e.g. installation of an interface) may have led to a crash when the response was not encoded. Add back a removed clause to the encoding reply function to fix it.
=> Realm Management: do not crash on synchronous operations

CHANGELOG.md
A `CHANGELOG.md` entry was incorrectly listed in the 1.0.5 release. Move it to 1.0.6, as it should have been.
=> Fix 1.0 changelog

.github/workflows/pr-container-build-workflow.yaml
Fix path to `pr-container-build-workflow.yaml`.
Update checkout action to the latest version to remove deprecation warnings.
=> [CI] Fix self reference in Test Container Builds workflow

doc/pages/tutorials/010-astarte_in_5_minutes.md
trying to pulling version `v1.0.4` returns
"Error response from daemon: manifest for astarte/astarte-stream-qt5-test:v1.0.4 not found: manifest unknown: manifest unknown"
on two machines I tried.
changing it to just `1.0.4` works as expected.
=> docs(5 minutes): fix `stream-qt5-test` version in docker commands

.gitignore, flake.lock, flake.nix, shell.nix
Init nix's development shell as an alternative to asdf. It can be used from both a standard nix-shell
or a nix develop with flakes.
MIX_HOME and HEX_HOME are set do directories in the project root to avoid conflicts with system packages.
~.envrc is provided for use with direnv, defaulting to the flake version of the shell.~
~To use environment variables in development, eg for testing, it is possible to create a `.env` file with said variables.
The syntax for said file can be found [here](https://github.com/bkeepers/dotenv) but in general it consists of lines of `VAR=value` pairs.~
[elixir-ls](https://github.com/elixir-lsp/elixir-ls) is provided (by default), with hooks tested working  for vscode and emacs (provided you don't hadn't previously installed elixir-ls through emacs' lsp-mode …
=> Init nix for development

apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml
Add the HTTP DELETE action supported by Realm Management in the Swagger document describing the possibility to delete a device from a realm by specifying its device ID.
=> Describe the device deletion API in the Realm Management's Swagger

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device_status.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/groups/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/device_status_view.ex, apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_by_alias_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_by_group_controller_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_controller_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
Deletion status is be displayed both for detailed device list and for device status.
Device details now include the `deletion_in_progress` field. In case of database error, it defaults to `false` (as done for the `connected` field).
Note that this implies one more query for each device, as the deletion status is stored in the deletion_in_progress table.
Close #881.
=> AppEngine: display device deletion status in details

CHANGELOG.md, apps/astarte_appengine_api/Dockerfile, apps/astarte_data_updater_plant/Dockerfile, apps/astarte_housekeeping/Dockerfile, apps/astarte_housekeeping_api/Dockerfile, apps/astarte_pairing/Dockerfile, apps/astarte_pairing_api/Dockerfile, apps/astarte_realm_management/Dockerfile, apps/astarte_realm_management_api/Dockerfile, apps/astarte_trigger_engine/Dockerfile
- Update docker images to Debian "bookworm".
- Contextually, move from libssl1.1 to the default Debian libssl package
- Add `USER nobody` to the Dockerfiles.
Closes #806, #807
=> Update docker images to `Debian bookworm` and add non-root user

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/payloads_decoder.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/payloads_decoder_test.exs
Due to a quirk in OTP's zlib library, the `safe_inflate/1` function can actually throw an error if the payload is malformed.
> In all functions errors, {'EXIT',{Reason,Backtrace}}, can be thrown, where Reason describes the error.
The unhandled error made the `DataUpdater` process crash, resulting in the malformed purge properties message being requeued and so on and so forth.
Fix this behaviour by wrapping relevant `:zlib` calls in a try-catch block.
=> DUP: do not crash when purge properties payload is not zlib deflated

apps/astarte_realm_management/lib/astarte_realm_management/device_removal/device_remover.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Device deletion was stuck in a loop when `individual_datastreams` and `individual_properties` tables were still not configured. Add a check for the presence of the two tables before trying to delete data from them. If they are not configured, move on.
Closes #885 .
=> RM: do not fail to delete device if there are no individual interfaces

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_data_consumer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex
Enhance DUP Logs Readability: Base64 Encode Astarte Payloads for Improved Decoding and Handling
Closes: #721
=> Enhance DUP Logs Readability: Base64 Encode Astarte Payloads for Improved Decoding and Handling

CHANGELOG.md, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/error_view.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/views/error_view.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/error_view.ex
Do not return an error 400 with message `"Internal server error"` if a request has an unparsable payload (e.g. a badly written CSR).
Return the more semantically correct `"Bad request"` message instead.
=> {Pairing, Housekeeping, RM} API: Handle `Bad Request`s

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/triggers_handler.ex, apps/astarte_data_updater_plant/mix.lock, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/triggers_handler_test.exs, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex, apps/astarte_trigger_engine/mix.lock
Now that astarte_core defines introspection as a map interface_name => %IntrospectionEntry{major: _, minor: _}
rather than a plaintext string in incoming introspection triggers, this should be handled in DUP and TE (see https://github.com/astarte-platform/astarte_core/pull/77).
AMQP trigger events are defined in astarte_core, while HTTP trigger events will return introspection as a JSON map interface_name -> {major, minor} instead of the plain introspection string sent by the device. 
It is possible to revert to the old behaviour by setting the `DATA_UPDATER_PLANT_GENERATE_LEGACY_INCOMING_INTROSPECTION_EVENTS` flag to `true` (default: `false`).
This change is thus BREAKING.
=> BREAKING: Incoming introspection event introspection map

apps/astarte_appengine_api/lib/astarte_appengine_api_web/plug/telemetry_calls_counter_plug.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/router.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/telemetry.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/plug/telemetry_calls_counter_plug.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/telemetry.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/plug/telemetry_calls_counter_plug.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/router.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/telemetry.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/plug/telemetry_calls_counter_plug.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/router.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/telemetry.ex
Add counter for APIs calls via a Plug, gouped by realm name, for the following services: appengine_api, housekeeping_api, pairing_api, realm_management_api
rewrote of routes for realm_management_api (endpoints has been kept the same)
resolve #897
=> Add telemetry counter for Astarte services APIs calls

apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/telemetry.ex
Add telemetry in order to record the cumulative amount of bytes from triggers payload, resolve #896
Add new astarte.trigger_engine.http_action_executed.payload_bytes metric
Change how triggers are handled to provide accurate metric logging for number of retries and payload size, both are cumulative.
Payload size is recorded even in case of  http error (for example, when configured API returns 500)
=> Metrics: expose the number of bytes sent by Trigger Engine

apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
Due to a typo, the previously added metric about trigger payload total bytes was not set correctly ([#899](https://github.com/astarte-platform/astarte/pull/899) ).
Affected app is Trigger Engine
This pr contains a fix
=> Trigger Engine: Fix typo in metric

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/telemetry.ex
Add device connection time as metric, based on latest device message/connection/disconnection/heartbeat
Expressed in microseconds
resolve #898
=> Data Updater Plant: Add metrics for device total connection time

CHANGELOG.md, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/config.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/test/support/astarte_housekeeping_mock.ex
Sometimes, on long operations (e.g. realm creation or deletion), synchronous calls may seem to fail because the underlying RPC to HK backend times out.
Introduce the `HOUSEKEEPING_API_RPC_TIMEOUT` env var to allow setting a longer timeout (in milliseconds). Default to 5  seconds, as before.
=> HK API: allow longer timeouts for calls to backend

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/device_status_by_alias_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/device_status_by_group_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/device_status_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/groups_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/interface_values_by_device_alias_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/interface_values_by_group_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/interface_values_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/router.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/router.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/controllers/agent_controller.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/controllers/device_controller.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/router.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/device_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_version_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/realm_config_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_policy_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/version_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/router.ex
Provide third-party applications with information about the version of Astarte microservices they are interacting with, enabling them to adapt their behavior based on the underlying service version.
Standardization of routers for the Astarte API endpoints to have a uniform Phoenix pipeline structure.
Add a ```/version``` endpoint to each microservice API, allowing third-party applications to query and retrieve the microservice version using the GET verb. Authentication is not required for accessing this endpoint. 
Standardize code for Astarte APIs by refactoring the router for endpoints. Remove plugs from controllers and incorporate them into the router pipeline.
By improving code readability in the app, astarte will expose information about the microservice version to third-party …
=> Astarte: update /version endpoint

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/state.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/engine.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/rpc/handler.ex, apps/astarte_housekeeping/mix.lock, apps/astarte_housekeeping/test/astarte_housekeeping/engine_test.exs, apps/astarte_housekeeping/test/astarte_housekeeping/queries_test.exs, apps/astarte_housekeeping/test/astarte_housekeeping/rpc/amqp_server_test.exs, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/non_negative_integer_or_unset_type.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/realm.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/fallback_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/realm_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/error_view.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/realm_view.ex, apps/astarte_housekeeping_api/mix.lock, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_housekeeping_api/test/astarte_housekeeping_api/realms/realms_test.exs, apps/astarte_housekeeping_api/test/astarte_housekeeping_api_web/controllers/realm_controller_test.exs, apps/astarte_housekeeping_api/test/support/astarte_housekeeping_mock.ex
While support for using a maximum period for datastreams data retention in a given realm is already present in DUP/AppEngine since 0.10, there was no support for setting its value.  Add it.
The value (in seconds) can be specified in Housekeeping API at realm creation, or changed with a realm update. When changed, it will apply oly to new data, i.e. data sent after the change.
Defaults to none, as before.
=> Set and enforce a maximum storage TTL for datastreams 

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management/mix.lock, apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs, apps/astarte_realm_management/test/support/database_fixtures.ex, apps/astarte_realm_management/test/support/database_test_helper.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api/realm_config/realm_config.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/fallback_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/realm_config_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/error_view.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/realm_config_view.ex, apps/astarte_realm_management_api/mix.lock, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/realm_config/realm_config_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/realm_config_controller_test.exs, apps/astarte_realm_management_api/test/support/astarte_realm_management_mock.ex, apps/astarte_realm_management_api/test/support/astarte_realm_management_mock_db.ex
Since we ~~will~~ allow to set/edit datastream max retention period in Housekeeping, add a way to retrieve its value in RM, too.
Moreover, as of today there are no checks  on whether an interface contains only mappings with `database_retention_ttl` lower than the maximum storage TTL allowed for the realm, making it possible to bypass the maximum allowed retention. Add this check on interface install and update. 
This change can be breaking, as some interfaces won't be installed anymore if the max allowed retention for the realm is set.
In the backend and RPC we use the Scylla [convention](https://opensource.docs.scylladb.com/stable/cql/time-to-live.html#notes) that TTL=0 means no TTL. However, the value given to the user if no maximum storage retention TTL is set will be the more …
=> RM: take maximum storage retention into account

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
Add cast to double in case of update of a server owned property, before sending data to device
Resolves first and second part of https://github.com/astarte-platform/astartectl/issues/239
=> Add support for double values in payload cast

CHANGELOG.md, apps/astarte_pairing/lib/astarte_pairing/queries.ex, apps/astarte_pairing/test/astarte_pairing/engine_test.exs, apps/astarte_pairing/test/support/database_test_helper.ex
When a device is unregistered and re-registered, the total sent bytes/messages counters are set to 0. This causes an inconsistency with bytes sent on interfaces. Fix this by not resetting counters. Fix #776.
Code is duplicated in `queries.ex` because string-based querying does not allow for much extensibility.
=> Pairing: do not reset device stats on re-registration

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/telemetry.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/error_view.ex, apps/astarte_pairing/lib/astarte_pairing/queries.ex, apps/astarte_pairing/test/astarte_pairing/engine_test.exs, apps/astarte_pairing/test/support/database_test_helper.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/views/error_view.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/error_view.ex
Forward-port a number of changes from release 1.0, most notably fixes when handling malformed payloads and server-side data, plus moving to a coherent semantics regarding device message count stats.
=> Forward-port changes from release 1.0

.github/workflows/astarte-apps-build-workflow.yaml
Use the codedcov action instead of the bash uploader, which seems quirky.
=> Workflows: fix codecov upload (hopefully)

apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/room.ex
The `Astarte.AppEngine.API.Config` module was removed from the alias list by chance, resulting in an `undefined` error when calling `Config.rooms_events_routing_key!/0`. Add it back.
=> AppEngine: access again `Config` in `rooms/room.ex`

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/trigger_policy/queries.ex
A query was missing the realm --> keyspace translation, resulting in crashes when `ASTARTE_INSTANCE_ID != ""`.
Fix it, thus closing #930.
=> DUP: do not crash on Data Updater process initialization

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex
Revert keyspace translation for interface delete and update.
Translation is now handled in Astarte Data Access
=> Revert keyspace translation for interface delete and update

doc/pages/architecture/062-trigger_delivery_policies.md
Please note: this PR has `release-1.1` as a base branch, let me know if it should be based on the `master` one.
=> Docs: fix typo on Trigger Policy page

apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_message_consumer.ex, doc/pages/architecture/062-trigger_delivery_policies.md
The message TTL argument for a policy (if set) was passed as-is to AMQP. However, TTLs in AMQP are in milliseconds, so a x1000 factor is added.
FIx relevant documentation, too.
=> Trigger Engine: trigger policy TTLs are seconds, not milliseconds!

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_message_consumer.ex, doc/pages/architecture/062-trigger_delivery_policies.md
Backport #950 into release-1.1.
=> Trigger policy TTL in seconds, also in release-1.1

apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_message_consumer.ex
[#951](https://github.com/astarte-platform/astarte/pull/951) fixed the TTL of policies, but it introduced a bug when to TTL was set due to Elixir's by-value evaluation strategy. Fix this by making the queue x-args generation lazy.
=> Trigger Engine: do not crash when trigger policy has no ttl

apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_message_consumer.ex
Fix a bug introduced in #952 where the TTL x-arg is not correctly generated leading to a crash.
=> Trigger Engine: do not crash when trigger policy has a ttl

apps/astarte_pairing/lib/astarte_pairing/engine.ex, apps/astarte_pairing/lib/astarte_pairing/queries.ex, apps/astarte_pairing/test/astarte_pairing/engine_test.exs
The device registration limit set for an Astarte realm is meant to prevent registration of new devices when the limit is reached. However, it blocked re-registration of already existing devices.
Allow to re-register existing devices without checking if registration limit has been reached.
Closes  [#933](https://github.com/astarte-platform/astarte/issues/933).
=> Pairing: allow re-registering devices even if limit is reached

CHANGELOG.md, apps/astarte_trigger_engine/lib/astarte_trigger_engine/policy/policy.ex, apps/astarte_trigger_engine/test/policy/policy_test.exs
Add :connection_error exception when handling a trigger policy response, then try to re-enqueue as 503 error
resolves https://github.com/astarte-platform/astarte/issues/936
=> TE: handle failure to connect to trigger target

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
Implemented `cast_value/2` functions to support string input parsing for `longinteger` values and arrays in server-owned interfaces. This implementation enables parsing of string inputs into integers where necessary.
Fixes #967
=> AppEngine: handle type casting for `longinteger` inputs

CHANGELOG.md, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management/mix.lock, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/interfaces.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_controller.ex, apps/astarte_realm_management_api/mix.lock, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_controller_test.exs, apps/astarte_realm_management_api/test/support/astarte_realm_management_mock.ex, apps/astarte_realm_management_api/test/support/astarte_realm_management_mock_db.ex
Add query for fetching all interfaces and its mappings from database
Fixes #970
=> List all interface definitions

.github/workflows/publish-release-to-dockerhub-workflow.yaml, .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml, .github/workflows/publish-tool-release-to-dockerhub-workflow.yaml, .github/workflows/publish-tool-snapshot-to-dockerhub-workflow.yaml
Since now we are using the new docker build infra, the old image building and publishing workflow, based on dockerhub runners, is broken.
Replace it with a new one, this time fully based on Github, to standardize the image publishing process.
`DOCKER_USERNAME` and `DOCKER_PASSWORD` of the registry must be added to repo secrets for this to work.
In order to separate the flow of tagged and untagged builds, workflows are splitted: one works only on tags, the other on everyday push events. Examples:
- When a change is merged into a release branch, say `release-1.2`, new images with `1.2-snapshot` tag are built and pushed to astarte's dockerhub;
- When a change is merged into the `master` branch, new images with `snapshot` tag are built and pushed to astarte's dockerhub;
- When a new Github …
=> Workflows: add build and push to Dockerhub workflow 

doc/pages/architecture/030-interface.md, doc/pages/architecture/040-interface_schema.md
Document that empty parameters are not allowed in a mapping.
Closes #983
=> docs: empty parameter is not allowed

tools/astarte_dev_tool/README.md, tools/astarte_dev_tool/lib/commands/dashboard/open.ex, tools/astarte_dev_tool/lib/mix/tasks/astarte_dev_tool/dashboard/open.ex, tools/astarte_dev_tool/lib/mix/tasks/astarte_dev_tool/system/down.ex, tools/astarte_dev_tool/lib/mix/tasks/astarte_dev_tool/system/up.ex, tools/astarte_dev_tool/lib/mix/tasks/astarte_dev_tool/system/watch.ex, tools/astarte_dev_tool/lib/utilities/auth.ex
Previous PRs contained documentation errors and could be improved at code level
* added existence check of `_private.pem` file
* checked the parameters of `mix astarte_dev_tool.dashboard.start`.
* various documentation fixes
=> FIX: errors from previous PRs #978 #982

doc/mix.exs, doc/pages/api/001-intro_api.md, doc/pages/user/052-using_channels.md
Specify in the Astarte Channels documentation page the AppEngine URL for the WebSocket channel.
=> chore(doc): add the websocket url for channels

doc/pages/user/001-intro_user.md
Nothing added to the changelog.
The documentation was succsessfully built with `mix docs` in the dev env.
The documentation of Astarte 1.1 was showing a warning stating that it was an unstable version. That was both wrong and misleading. Remove that statement.
=> [Doc] Astarte 1.1 is stable. Remove the "unstable" warning.

tools/astarte_dev_tool/lib/constants/system.ex, tools/astarte_dev_tool/lib/mix/tasks/astarte_dev_tool/system/up.ex, tools/astarte_dev_tool/lib/utilities/process.ex, tools/astarte_dev_tool/test/astarte_dev_tool_test.exs, tools/astarte_dev_tool/test/system_test.exs
* [ X] I have read [CONTRIBUTING.md](../CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](../CODE_OF_CONDUCT.md)
* [X ] I have added to [CHANGELOG.md](../CHANGELOG.md) relevant changes and any other user facing change
* [ X] I have added or ran the appropriate tests
--watch with a --detach flag is deprecated since  2.27.2,  docker compose refuses to "up" with  those flags
This PR fixes this behavior
=> Remove --watch with --detach options in docker compose up

tools/astarte_dev_tool/lib/commands/auth/keys.ex, tools/astarte_dev_tool/lib/mix/tasks/astarte_dev_tool/auth/keys.ex, tools/astarte_dev_tool/lib/utilities/auth.ex, tools/astarte_dev_tool/lib/utilities/process.ex, tools/astarte_dev_tool/mix.exs, tools/astarte_dev_tool/test/astarte_dev_tool_test.exs
This PR introduces the feature for generating public and private keys using the `mix astarte_dev_tool.auth.keys` task. This task allows the creation of both private and public keys, as well as the option to derive a public key from a provided private key using `arg`.
The feature enhances key management within the development tooling, enabling easy and streamlined keypair generation for authentication and security purposes.
```bash
$ mix astarte_dev_tool.auth.key
$ mix astarte_dev_tool.auth.key "-----BEGIN EC PRIVATE KEY-----Base64-----END EC PRIVATE KEY-----"
$ mix astarte_dev_tool.auth.key "$(mix astarte_dev_tool.auth.key)"
```
Nothing
The feature includes two main functionalities:
- Generating a new keypair (both private and public keys).
- Deriving a public key from a given private key …
=> `astarte-dev-tool` Added generating private/public keys feature

CHANGELOG.md, README.md, apps/astarte_appengine_api/mix.exs, apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_data_updater_plant/mix.exs, apps/astarte_housekeeping/mix.exs, apps/astarte_housekeeping_api/mix.exs, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_pairing/mix.exs, apps/astarte_pairing_api/mix.exs, apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml, apps/astarte_realm_management/mix.exs, apps/astarte_realm_management_api/mix.exs, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_trigger_engine/mix.exs, doc/mix.exs, tools/astarte_device_fleet_simulator/mix.exs, tools/astarte_e2e/mix.exs, tools/astarte_export/mix.exs, tools/astarte_import/mix.exs
Update the readme, mix.exs and OpenAPI files to refer to the new Astarte dev version 1.3.0-dev.
=> Prepare 1.3.0 development cycle

doc/swagger-ui-index.html
v1.2.0 is the stable release, we're on master and docs should reflect that.
=> Docs: point Swagger URLs to master

CHANGELOG.md, tools/astarte_import/README.md, tools/astarte_import/lib/astarte/import.ex, tools/astarte_import/lib/astarte/import/populatedb.ex
The current import functionality fails when encountering unsupported data types, which can lead to incomplete or incorrect imports. This fix ensures that unsupported data types are handled gracefully.
- Added checks for unsupported data types in the import process.
- Implemented error handling to log and skip unsupported data types instead of failing the entire import.
Manual testing has been conducted to ensure the import process completes successfully even when unsupported data types are encountered.
This PR addresses an issue with the unsupported data types during the import process in Astarte.
Fixes #
```docs
```
=> Fix unsupported data types in Astarte import

.github/workflows/publish-release-to-dockerhub-workflow.yaml, .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml
Workflows publishing images to Dockerhub did not run up to the publishing step because they depended on the apps test workflow, which did always fail because it could not access the codecov token secret when called via another workflow. Allow the apps test workflow to inherit secrets from the calling workflow (see [here](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow)), so that it can successfully run again and unlock the publisher workflow.
Allow the CI to build&push images to Dockerhub again
```docs
```
=> Workflows: allow to publish images to Dockerhub again

apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_controller_test.exs, apps/astarte_trigger_engine/test/amqp_consumer/amqp_consumer_tracker_test.exs
This PR aims to resolve flakiness for trigger_engine tests (due to a delay in data synchronization) and realm_management_api test (due to a flaw in tests setup)
=> Resolve test flakiness

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/application.ex
Do not use just the `host` option to let the consumer connect to AMQP, use the full opts set.
Allow to connect to any AMQP broker.
```docs
```
=> DUP: use all connection options for AMQP

.env, CHANGELOG.md, docker-compose.yml
Your Astarte instance created by docker-compose can now be exposed on an arbitrary base domain. This is made possible by the addition of the .env file that feeds env vars to the docker compose file. The compose.env file is deleted and its content migrated to .env.
Fixes #1024
=> Allow to reach your docker-compose instance from outside your host

tools/astarte_export/lib/astarte/fetchdata/fetchdata.ex, tools/astarte_export/lib/astarte/xml_generate.ex
Enhancements to XML and data type handling in astarte/tools/astarte_export
Improvements to XML generation:
astarte/tools/astarte_export/lib/xml_generate.ex:
- Enhanced xml_write_full_element function to handle lists and simple values.
- Added iteration through list elements to generate sub-elements dynamically.
- Simplified handling for non-list values by encoding them directly.
Improvements to data type conversion:
astarte/tools/astarte_export/lib/fetchdata/fetchdata.ex:
- Refactored from_native_type function for :binaryblob to use pattern matching, improving robustness and handling invalid binary values gracefully.
- Added support for array types like :binaryblobarray, :booleanarray, :datetimearray, and others, leveraging Enum.map for efficient conversion.
The primary goal of these …
=> AstarteExport:  XML generation and type handling

tools/astarte_export/lib/astarte/fetchdata/fetchdata.ex, tools/astarte_export/test/astarte_export_test.exs
To ensure consistency between the export and import processes. Renames the key of the interface attribute from `"interface_name"` to `"name"`. Standardizes the output of `astarte_export` to match the import file format used by `astarte_import`.
Closes: #1026
Fixes #
```docs
```
=> AstarteExport: Rename interface attribute key

tools/astarte_export/lib/astarte/export.ex, tools/astarte_export/lib/astarte/fetchdata/fetchdata.ex, tools/astarte_export/lib/astarte/fetchdata/queries/queries.ex
Adds functionality to fetch endpoint paths for data mappings.
Updates the related processing logic to support the new fetched paths.
To ensure data mappings are dynamically handled based on the correct endpoint paths.
To improve the data processing logic's flexibility and accuracy, ensure it works with the updated endpoint paths.
Closes #1028
Fixes #
Closes #1028
Fetching data from the table `individual_property`. Aggregation object data is filtered using `device_id` and `interface_id`. The aggregation of individuals adds one more argument: `endpoint_id`.
```docs
```
=> Astarte export: Add support for parametric interfaces

apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/support/database_test_helper.exs
`samplingPeriod` is declared as a double in `create_server_owned_aggregated_object_table/1`, but the endpoint is declared as an integer
the endpoint type is changed to match the database type
This is a needed fix for using (e)xandra, as otherwise the tests would fail because [xandra requires float values when the database type is a double](https://github.com/whatyouhide/xandra/blob/42e8b26cf6f2e55de9b087cb2fa9f9388e9f5f50/lib/xandra/protocol/v4.ex#L305)
```docs
```
=> test(appengine): consistently define endpoint types

CHANGELOG.md, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs
In some corner cases, e.g. deletion of a disconnected device, Astarte would generate a disconnection trigger even if
the device is already disconnected.
Avoid doing so by checking the device connection state before generating a trigger.
Fixes #1014
```docs
```
=> DUP: do not generate redundant disconnection triggers

docker-compose.yml
New version of `vernemq` container needs `start_vernemq` command
Does the job
=> fix: vernemq command changed to start_vernemq

apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/fallback_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/error_view.ex, apps/astarte_appengine_api/priv/static/astarte_appengine_api.yaml, apps/astarte_appengine_api/test/astarte_appengine_api_web/auth/auth_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/groups_controller_test.exs, apps/astarte_appengine_api/test/support/jwt_test_helper.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/controllers/fallback_controller.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/views/error_view.ex, apps/astarte_housekeeping_api/priv/static/astarte_housekeeping_api.yaml, apps/astarte_housekeeping_api/test/astarte_housekeeping_api_web/auth/auth_test.exs, apps/astarte_housekeeping_api/test/support/jwt_test_helper.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/controllers/fallback_controller.ex, apps/astarte_pairing_api/lib/astarte_pairing_api_web/views/error_view.ex, apps/astarte_pairing_api/priv/static/astarte_pairing_api.yaml, apps/astarte_pairing_api/test/astarte_pairing_api_web/auth/auth_test.exs, apps/astarte_pairing_api/test/astarte_pairing_api_web/controllers/agent_controller_test.exs, apps/astarte_pairing_api/test/support/jwt_test_helper.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/fallback_controller.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/error_view.ex, apps/astarte_realm_management_api/priv/static/astarte_realm_management_api.yaml, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/auth/auth_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/device_controller_test.exs, apps/astarte_realm_management_api/test/support/jwt_test_helper.ex
- Expand the ```fallback_controller``` with some ```auth_error``` functions
- Add additional error views with useful feedback messages
- Add the ```gen_jwt_token_with_wrong_signature``` function in the ```JWTTestHelper```
- Add the necessary auth tests and adapt existing ones
- Add new errors to the OpenAPI schema of every app
Fixes: #1031 
-
None
=> Handle API authentication errors for the API services

CHANGELOG.md, tools/astarte_export/README.md, tools/astarte_export/lib/astarte/export.ex, tools/astarte_export/lib/astarte/fetchdata/fetchdata.ex, tools/astarte_export/lib/astarte/fetchdata/queries/queries.ex, tools/astarte_export/lib/mix/tasks/astarte_export.ex
* [`tools/astarte_export/lib/astarte/export.ex`](diffhunk://#diff-02207ec611cfd12f45fc5ef9ba78740251937cc34b75dd5260940ede37f765d1R50-R57): Added `export_realm_data_by_device_id/3` to export data for a specific device ID and corresponding helper functions (`generate_xml_by_device_id/3`, `process_devices_by_device_id/5`, `process_devices_by_device_id/6`). [[1]](diffhunk://#diff-02207ec611cfd12f45fc5ef9ba78740251937cc34b75dd5260940ede37f765d1R50-R57) [[2]](diffhunk://#diff-02207ec611cfd12f45fc5ef9ba78740251937cc34b75dd5260940ede37f765d1R78-R125)
* [`tools/astarte_export/lib/astarte/fetchdata/fetchdata.ex`](diffhunk://#diff-83c27e89ef06e3b054c9193e03f133222f2c7a863d2db8a33600eb1691095465R41-R59): Added `fetch_device_data_by_device_id/4` to fetch data for a specific device ID.
* …
=> Astarte export: astarte export by device_id

docker-compose.dev.yml, docker-compose.yml
The change improves the development experience via `docker-compose.dev`. 
- The image build has been moved inside the `docker-compose.dev` file. 
- The ports of `scylladb` have been opened to allow connection from the host
- Development instances of `scylladb` have been reduced to one, as per the official site
`astarte-dev-tool` can now connect to the db locally
=> feature: docker-compose.dev improvement

.gitignore, apps/astarte_appengine_api/.devcontainer/devcontainer.json, apps/astarte_appengine_api/.devcontainer/docker-compose.override.yml, apps/astarte_data_updater_plant/.devcontainer/devcontainer.json, apps/astarte_data_updater_plant/.devcontainer/docker-compose.override.yml, apps/astarte_housekeeping/.devcontainer/devcontainer.json, apps/astarte_housekeeping/.devcontainer/docker-compose.override.yml, apps/astarte_housekeeping_api/.devcontainer/devcontainer.json, apps/astarte_housekeeping_api/.devcontainer/docker-compose.override.yml, apps/astarte_pairing/.devcontainer/devcontainer.json, apps/astarte_pairing/.devcontainer/docker-compose.override.yml, apps/astarte_pairing_api/.devcontainer/devcontainer.json, apps/astarte_pairing_api/.devcontainer/docker-compose.override.yml, apps/astarte_realm_management/.devcontainer/devcontainer.json, apps/astarte_realm_management/.devcontainer/docker-compose.override.yml, apps/astarte_realm_management_api/.devcontainer/devcontainer.json, apps/astarte_realm_management_api/.devcontainer/docker-compose.override.yml, apps/astarte_trigger_engine/.devcontainer/devcontainer.json, apps/astarte_trigger_engine/.devcontainer/docker-compose.override.yml
Enhance MacOS Compatibility and Development Setup
- Added `devcontainer` to work on VSCode
- Added .DS_Store ignore
=> (feature): MacOS porting

CHANGELOG.md, apps/astarte_appengine_api/lib/astarte_appengine_api/auth/auth.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/queries.ex, apps/astarte_pairing/lib/astarte_pairing/engine.ex, apps/astarte_pairing/lib/astarte_pairing/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
When connection to the database is sometimes unstable, it was possible that failure to retrieve the public key made
users unable to use APIs - as backend services crashed while checking authorization.
This seemed to be a problem with CQEx, so replace it with the Xandra driver.
This change applies to AppEngine, Realm Management and Pairing.
Fixes #
```docs
```
=> Backends: fix corner case error in public key retrieval

.github/workflows/publish-release-to-dockerhub-workflow.yaml, .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml, Dockerfile
This change adds support for building Astarte services targeting specific architectures.
The CI workflows are updated to setup buildx, a Docker CLI plugin for extended build capabilities with BuildKit, and to build multi-arch Docker images.
The targeted platforms are: linux/amd64 and linux/arm64.
=> Setup CI for multi-arch builds

.github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/astarte-end-to-end-test-workflow.yaml
CI for new PRs fails due to unmaintained `actions/cache@v1`, this pr bumps up the cache version to v4.
=> chore(workflows): update cache version to v4

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/endpoint.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/simple_trigger.ex, apps/astarte_realm_management/lib/astarte_realm_management/repo.ex, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
Based on #1078, see there for context.
Moves the `SELECT` queries to exandra, modifiying the functions signatures where needed, while trying not to change the return types.
=> feat(exandra): move realm management select queries to exandra

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/endpoint.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/simple_trigger.ex, apps/astarte_realm_management/lib/astarte_realm_management/repo.ex, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
Moving the remaining `SELECT` queries from `CQEx` to  `Exandra`, based on #1080 (see there for context).
=> chore(exandra): move remaining `SELECT` queries in `realm_management` from `CQEx` to `Exandra`

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/repo.ex
Refactor to let the `Repo` handle raised exceptions rather than crashing on queries changed in #1084.
Only queries where the function API was changed in #1084 were touched.
=> DUP: refactor to catch Xandra exceptions on (new) Ecto queries

apps/astarte_realm_management/lib/astarte_realm_management/repo.ex, apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs
- Realm Management :: does not handle Xandra errors anymore in the repo itself, it will be the rpc caller to do so.
=> feat(RM): let it crash!

apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/deletion_in_progress.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/device.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/grouped_device.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/name.ex
Moves the remaining `SELECT` queries to `exandra` and `ecto`
=> refactor(realm_management): move remaining `SELECT` queries to `exandra` and `ecto`

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/endpoint.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/interface.ex, apps/astarte_realm_management/lib/astarte_realm_management/repo.ex, apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
Based on #1089 to have a unified `fetch_*` interface.
- Moves `insert_mapping_query` in realm management to exandra
- `install_new_interface` interaction with the database moved to
`exandra`
- `update_interface` interaction with the database moved to `exandra`
- removed custom batch, using `Exandra.execute_batch`
=> refactor(exandra): insert and update interface

apps/astarte_realm_management/test/astarte_realm_management/engine_test.exs, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
integrates the new behavior for when the keyspace is not found in tests: raise instead of returning an `{:error, _}` tuple.
=> fix(test): new keyspace not found behavior

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
moves `delete_devices_with_data_on_interface` to use `exandra` and `ecto`
=> refactor(RM): move delete_devices_with_data_on_interface

apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
other services use 4 digits for the submillis while in appengine we use 3.
still, the old method used div(1000) for the timestamp and rem(100) for the submillis
if we do the math, we notice things don't quite match
- 1234567890 |> div(1000) = 1234567
- 1234567890 |> rem(100) = 90
the 8 is missing.
Fixes #
```docs
```
=> fix(appengine): submillis consistency

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
previously, timestamps in `insert_path_into_db` would use the wrong unit and as a result, reception_timestamp would be dated in 1970 and value_timestamp is a valid timestamp but at microsecond precision
Fixes #
```docs
```
=> fix(appengine): server owned datastreams path timestamps

apps/astarte_realm_management/lib/astarte_realm_management/astarte/kv_store.ex, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Based on #1103, see there for context
Moves `install_trigger_policy` to `exandra` and `ecto`
=> refactor(RM): move install_trigger_policy_link

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Based on #1105 
Moves `delete_trigger_policy_link` to `exandra` and `ecto`
=> refactor(RM): move `delete_trigger_policy_link`

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs
The `/value` endpoint in the `com.example.TestObject` interface is defined to handle `double` data. However, in tests it received an integer value. This worked due to a bug in the CQex driver.
Similar to https://github.com/astarte-platform/astarte/pull/1044.
Be consistent with the type declared and use a float instead of an integer, and update the bytes count consequently.
=> DUP tests: consistently define object aggregated value types

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/repo.ex
Same old, same old: replace the unsupported CQEx driver with Ecto (specifically, to use the Exandra adapter).
This also implies some refactor, as we don't need to pass around the CQEx client anymore. 
The API of existing query functions is kept as it was.
=> DUP: move UPDATE queries from CQEx to Ecto

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
based on #1097 
moves `delete_interface_storage` to use `exandra` and `ecto`
=> refactor(RM): move delete_interface_storage

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Based on #1107 
Moves `delete_simple_trigger` to `exandra` and `ecto`
=> refactor(RM): move delete_simple_trigger

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/repo.ex
Same old, same old: replace the unsupported CQEx driver with Ecto (specifically, to use the Exandra adapter).
This also implies some refactor, as we don't need to pass around the CQEx client anymore.
Also, fix a typo in the `Queries.insert_value_into_db` where a `%Mapping{}` was incorrectly referenced to as `endpoint` (yes, `insert` might perform a deletion).
The API of existing query functions is kept as it was.
~~This PR is based, based on #1093.~~
=> DUP: move DELETE queries to Ecto 

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
Moves `update_jwt_public_key_pem` to `exandra` and `ecto`
=> refactor(RM): move `update_jwt_public_key_pem`

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/repo.ex
Some relevant comments were left after a merged PR. Implement them.
See @noaccOS  comments in #1104 .
=> DUP: use a more elegant style when handling some queries

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/repo.ex
Same old, same old: replace the unsupported CQEx driver with Ecto (specifically, to use the Exandra adapter).
This also implies some refactor, as we don't need to pass around the CQEx client anymore.
This final PR removes CQEx from DUP's `lib/` directory.
Apart from the obvious, two small changes are significant:
- Data from unreliable mappings are inserted with ONE consistency instead of ANY, as it is not suppoted by Exandra (see `Queries.insert_value_into_db` and https://github.com/whatyouhide/xandra/issues/380)
- `Queries.fetch_path_expiry` uses once again `datetime_value` as reference field. Not using it was a mistake from a previous PR.
The API of existing query functions is kept as it was.
=>  DUP: move INSERT queries from CQEx to Ecto

apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/kv_store.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/repo.ex
using the standard ecto functions, there is no way to get the sql and params for an insertion from the adapter, which is instead the case for every other query type.
this pr defines a function, `insert_to_sql`, which behaves a bit like `to_sql` for insertions.
instead of using `Exandra.Connection.insert`, the logic was re-implemented here as for the little effort of copy-pasting the logic here, we get the added benefit of being able to declare custom syntax for the parameters, like using `intAsBlob(?)` for an insertion in the KvStore, while exandra is limited to just `?` directly.
Fixes #
```docs
```
=> refactor(appengine): centralize insert to sql definition

apps/astarte_realm_management/lib/astarte_realm_management/bigint.ex, apps/astarte_realm_management/lib/astarte_realm_management/c_system.ex, apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/device.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/endpoint.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/grouped_device.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/individual_datastream.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/individual_properties.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/interface.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/name.ex, apps/astarte_realm_management/lib/astarte_realm_management/realms/simple_trigger.ex, apps/astarte_realm_management/lib/astarte_realm_management/smallint.ex, apps/astarte_realm_management/lib/astarte_realm_management/uuid.ex, apps/astarte_realm_management/priv/repo/migrations/20250305120046_create_datastream_individual_multi_interface.exs, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
- `UUID` modules moved to `Astarte.RealmManagement.UUID` (was `Astarte.DataAccess.UUID`). individual properties and individual datastream use the appropriate scylla types for their fields.
- Migrations to install and update interfaces are run trough the `Repo` module instead of `CQEx`
=> refactor(RM): runtime migrations to `exandra`

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device_status.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/device_status_by_group_controller_test.exs
Preparation commits for #1057.
- add a function to device queries to return the device to then build the status. This is needed to be able to build the device_status struct in a second moment.
- Have `DeviceStatus.from_db_row` trim the timestamps to millisecond precision, like the version in the Queries module. This also restores a test from before the refactors done lately.
Fixes #
```docs
```
=> refactor(device): preparations for merge_device_status

.github/workflows/astarte-appengine-api-workflow.yaml, .github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/astarte-data-updater-plant-workflow.yaml, .github/workflows/astarte-housekeeping-api-workflow.yaml, .github/workflows/astarte-housekeeping-workflow.yaml, .github/workflows/astarte-pairing-api-workflow.yaml, .github/workflows/astarte-pairing-workflow.yaml, .github/workflows/astarte-realm-management-api-workflow.yaml, .github/workflows/astarte-realm-management-workflow.yaml, .github/workflows/astarte-trigger-engine-workflow.yaml
Up to now build test and coverage workflows were triggered on every app on every code change. This was quite wasteful in terms of resources, as unnecessary checks were run on unchanged code.
This PR separates the workflows of every app into its own workflow, that gets triggered only when there are some changes in the relevant application.
`api` application's workflows get also triggered when there is a change in the non-`api` counterpart (to ensure that the communication between the two is consistent).
=> ci(CI): refactor Astarte CI

apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/test/astarte_realm_management/queries_test.exs
Porting all DELETE queries with Xandra to Exandra
=> refactor(RM): move xandra delete to exandra

.github/workflows/astarte-appengine-api-workflow.yaml, .github/workflows/astarte-apps-build-workflow.yaml, .github/workflows/astarte-data-updater-plant-workflow.yaml, .github/workflows/astarte-housekeeping-api-workflow.yaml, .github/workflows/astarte-housekeeping-workflow.yaml, .github/workflows/astarte-pairing-api-workflow.yaml, .github/workflows/astarte-pairing-workflow.yaml, .github/workflows/astarte-realm-management-api-workflow.yaml, .github/workflows/astarte-realm-management-workflow.yaml, .github/workflows/astarte-trigger-engine-workflow.yaml
- The current workflow is a template, it runs only for those apps that
have an actual change in a PR/branch create/pull request
- Each serve has its own file that only calls the template, there the
action takes place
Forward port from release-1.1 (see PR #1124 for context), revisits CI to run only on code changes.
=> chore(CI): Run CI only on code change

apps/astarte_appengine_api/lib/astarte_appengine_api/auth/auth.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/groups/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/health.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/realms/realm.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/stats/queries.ex
Fix astarte keyspace encoding, check and fix for functions that used to require a plain or encoded realm name in order to generally have:
def functions -> accepts plain realm name, encode into keyspace and then use that
defp -> accepts only keyspaces
There are actually one or two occurrences that require a rework to match the above case(s), but this would affect the entire application logic (maybe in another PR?)
=> Move keyspace translations to public functions in query files

apps/astarte_pairing/lib/astarte_pairing/queries.ex, apps/astarte_pairing/test/astarte_pairing/engine_test.exs, apps/astarte_pairing/test/astarte_pairing/rpc/handler_test.exs
This change avoids catching and managing Xandra errors within the Pairing code dedicated to interacting with the database, where the concern does not require handling expections.
Exceptions and temporary failures are better handled by whomever calls Pairing functionality: in this case RPC, in the future it might be directly a Phoenix conn handling a request.
Note that Astarte RPC already handles failures by responding with a generic error to the caller.
The exception is logged for operational purposes, so developers can troubleshoot the issue, but these kind of database errors are not of much use to API users.
=> Pairing: let it crash on database errors

.github/workflows/astarte-appengine-api-workflow.yaml, .github/workflows/astarte-data-updater-plant-workflow.yaml, .github/workflows/astarte-housekeeping-api-workflow.yaml, .github/workflows/astarte-housekeeping-workflow.yaml, .github/workflows/astarte-pairing-api-workflow.yaml, .github/workflows/astarte-pairing-workflow.yaml, .github/workflows/astarte-realm-management-api-workflow.yaml, .github/workflows/astarte-realm-management-workflow.yaml, .github/workflows/astarte-trigger-engine-workflow.yaml
Single services CI workflows did not run because github did not match subfolders with only parent folder name. Fixing
=> fix(CI): Match services folders

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
a regression was introduced in 2c66918c1ba02e93566af1762e3203c1f591df0e, where timestamps were in millisecond precision, but `DateTime.from_unix!` was given microsecond precision. This caused datetimes to be incorrect.
this was the result after setting up astarte in 5 minutes and running astarte-stream-qt5-test
```
❯ docker compose exec -it scylla cqlsh -e 'select last_connection from test.devices;'
last_connection
---------------------------------
1970-01-21 03:48:22.216000+0000
```
Fixes #
```docs
```
=> fix(dup): last_connection / last_disconnection timestamp unit

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
previously string keys were given to exandra in `insert_all`. however, when given an actual schema (ie, not a string with a table name), ecto expects atom keys for the values.
this resulted in a crash with the log
%ArgumentError{message: \"unknown field `"group"` in schema Astarte.DataUpdaterPlant.DataUpdater.KvStore given to insert_all. ...}
the fix is to just use atom keys
Fixes #
```docs
```
=> fix(dup): don't crash on register_device_with_interface

apps/astarte_appengine_api/lib/astarte_appengine_api/device/aliases.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/attributes.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
rewrite merge_device_status to use changesets to minimize the number
of queries performed.
refactor some private functions in their own modules.
~depends on #1056~
~depends on #1128~
Fixes #
```docs
```
=> refactor(appengine): use changesets in merge_device_status

apps/astarte_appengine_api/lib/astarte_appengine_api/datetime.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/devices/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/realms/individual_datastream.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/realms/individual_property.ex
using integer timestamps, especially when doing calculations on them,
is error prone and we've just recently resolved a bug that was caused
by a double "microsecond to millisecond" conversion.
elixir has something more solid than that: `DateTime`s.
default Ecto types only allow full second or microsecond precision,
but cql timestamps use millisecond precision. To avoid precision errors,
a new Ecto DateTime type has been created, which allows millisecond
precision (althogh no check is made: Xandra handles that itself).
although currently unused, the submillis should now use the correct
number of digits.
an unused and nonfunctioning function in `IndividualProperty` has been
removed
Fixes submillis precision probably?
```docs
```
=> refactor(appengine): use datetimes for data insertion

apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex
A regression was introduced that made AE crash on some device status queries (merge_device_status, deletion in progress check, list aliases). Fix it.
=> AE: do not crash on some device status queries

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
A regression was introduced in which the individual_properties column queried when (re)sending properties to the device was named with the type instead of the actual column name. Fix it.
=> DUP: do not crash when resending properties to device

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
previously, Repo.update_all was used, which returns a tuple in the form `{integer(), any()}`, which was not matched by Queries' functions and made impl crash at line 188 for a failed match to `:ok`
Fixes #
```docs
```
=> fix(dup): device deletion queries

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Remove unused Database connection coming from `Astarte.DataAccess.Database` in
`engine.ex` and `queries.ex`.
=> (RM) remove unused CQEx database connection

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/trigger_policy/queries.ex
See https://github.com/astarte-platform/astarte_data_access/pull/98. Use the standard consistency classes as defined there:
- "Domain Model": operations related to all Astarte entities, such as triggers, interfaces, policies etc
- "Device Info": operations related to Device metadata (e.g. connection status), time series metadata (as they refer to a specific device), property data (as they specify the domain specific status of a device)
- "Time series": operations related to datastreams
Use the standard approach to CL, instead of a case-by-case one.
=> DUP: use standard CL for queries

apps/astarte_realm_management/lib/astarte_realm_management/c_system.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
See https://github.com/astarte-platform/astarte_data_access/pull/98. Use the standard consistency classes as defined there:
- "Domain Model": operations related to all Astarte entities, such as triggers, interfaces, policies etc
- "Device Info": operations related to Device metadata (e.g. connection status), time series metadata (as they refer to a specific device), property data (as they specify the domain specific status of a device)
- "Time series": operations related to datastreams
Note that, in the specific context of device deletion, we use the `device_info` class. When a device is deleted, all messages that it sent or received on interfaces have to be deleted, other than all its information (e.g. aliases, groups, ...). In order to be consistent in the whole deletion operation, we …
=> Realm Management: use standard CL for queries

apps/astarte_housekeeping/lib/astarte_housekeeping/c_system.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/migrator.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/queries.ex, apps/astarte_pairing/lib/astarte_pairing/queries.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/queries.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/events_consumer.ex
See https://github.com/astarte-platform/astarte_data_access/pull/98. Use the standard consistency classes as defined there:
- "Domain Model": operations related to all Astarte entities, such as triggers, interfaces, policies etc
- "Device Info": operations related to Device metadata (e.g. connection status), time series metadata (as they refer to a specific device), property data (as they specify the domain specific status of a device)
- "Time series": operations related to datastreams
See also #1146 
Use the standard approach to CL, instead of a case-by-case one.
This PR groups together changes to minor Astarte services (Trigger Engine, Housekeeping, Pairing) in order to move faster
=> Backends: Use standard consistency levels in queries

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/groups/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/stats/queries.ex
Moved consistency management to `data_access` `Consistency` module, in compliance with other astarte modules, see astarte-platform/astarte_data_access#98 #1154 #1153 for more reference
Supersede #1157
=> chore(AE): use standard CL for queries

apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
Bug:
Internal server error occurred when trying to open a trigger to view, due to two issues:
1. The UUID was not being properly converted to a string, causing a type mismatch in the query.
2. The query used the incorrect field name `groups` instead of `group`, which caused it to fail when fetching data from the database.
Fix:
- Ensures proper conversion of UUIDs to strings by using `:uuid.uuid_to_string` with the `:binary_standard` format.
- Fixed the typo in the query by changing `groups` to `group`.
=> fix(RM): Resolve UUID format issue and correct query filtering

apps/astarte_appengine_api/lib/astarte_appengine_api/config.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/config/clustering_strategy.ex, apps/astarte_appengine_api/rel/env.sh.eex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config/clustering_strategy.ex, apps/astarte_data_updater_plant/rel/env.sh.eex
Kubernetes clustering strategies were misconfigured and required to an unnecessary update from the operator. This PR introduces the necessary fixes to solve 2 main issues:
- DUP clustering strategy should only be responsible for finding other DUP instances. Up to not a general clustering approach was used to allow all nodes to find each other. What we actually want to do is allow DUP instances to find each other and leave to appegine to find DUP instances to talk to (that logic is in fact moved into appengine). DUP clustering strategy now only tries to find other DUP nodes and by default leverages already available endpoint labels to query the kubernetes API.
- As anticipated, AppEngine instances should only be responsible for finding DUP instances. With this changes they not try anymore …
=> fix: kubernetes clustering

apps/astarte_appengine_api/Dockerfile, apps/astarte_data_updater_plant/Dockerfile, apps/astarte_housekeeping/Dockerfile, apps/astarte_housekeeping_api/Dockerfile, apps/astarte_pairing/Dockerfile, apps/astarte_pairing_api/Dockerfile, apps/astarte_realm_management/Dockerfile, apps/astarte_realm_management_api/Dockerfile, apps/astarte_trigger_engine/Dockerfile
Fix two warnings found in the Dockerfiles of multiple apps:
1. **FromAsCasing**: The `as` keyword casing was inconsistent. This has been fixed by updating the `as` keyword to match the correct casing convention.
2. **LegacyKeyValueFormat**: The format used for setting environment variables with `ENV` was outdated. The legacy `ENV key value` format has been updated to the proper `ENV key=value` format.
These changes help eliminate the warnings and ensure the Dockerfiles are compliant with best practices.
=> Fix Dockerfile Warnings for Casing and ENV Format

apps/astarte_appengine_api/lib/astarte_appengine_api/config.ex
Clustering-related environment variables were incorrectly labeled as `data_updater_plant` configurations. This did not create any problem for now but was not consistent with the rest of the environment variables configuration.
=> fix(AE): incorrect skogsra config

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex
This PR introduces a libcluster topology to enable the DUP service to automatically discover and connect to all VerneMQ replicas across different environments.
- Docker-compose: a topology tailored for this environment is added, relying on DNS facilities provided by Docker to discover VerneMQ nodes at known domain names, i.e. the name of the VerneMQ service as defined in docker-compose.yaml.
- Kubernetes: for production scenarios, VerneMQ is deployed by the Astarte Operator as a StatefulSet. As such, the libcluster strategy attempts first attempts to discover node IPs by querying for app labels, as in the other Kubernetes strategy already defined. Then it assumes specific names for the Erlang nodes using the discovered IPs and the fact that nodes in the StatefulSet have deterministic …
=> Add libcluster topology for VerneMQ discovery in DUP

apps/astarte_appengine_api/lib/astarte_appengine_api/config.ex
Similar to #1190 
Adds support for VerneMQ node discovery in an astarte clustering, leveraging `libcluster` configuration
=> feat(AE): VerneMQ node discovery

apps/astarte_appengine_api/config/test.exs, apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rpc/vmq_plugin.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rpc/vmq_plugin/behaviour.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/rpc/vmq_plugin/client.ex, apps/astarte_appengine_api/test/astarte_appengine_api/data_transmitter_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api/device/device_test.exs, apps/astarte_appengine_api/test/astarte_appengine_api_web/channels/rooms_channel_test.exs
Based on #1191
Requires astarte-platform/astarte_vmq_plugin#102
This PR moves the communication between AppEngine and the Astarte VerneMQ Plugin outside of `astarte_rpc`. The new strategy consists in having an rpc server shared among all VerneMQ Plugin replicas (see astarte-platform/astarte_vmq_plugin#102 for context) and making RPC calls to shuch server. AppEngine calls have to be reworked to accomodate for the changes
=> refactor(AE): VerneMQ RPC

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
DUP crashes when writing individual-aggregated binaryblobs (or arrays thereof) due to the fact that binaryblobs are decoded as `%Cyanide.Binary{}` structs.
Handle `%Cyanide.Binary{}` structs when writing individual values, just as we do when we handle object values.
Fixes #1187
=> DUP: do not crash on binaryblob insertion

apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_consumer_tracker.ex, apps/astarte_trigger_engine/test/amqp_consumer/amqp_consumer_tracker_test.exs
6 second sleeps were introduced as a way to mitigate a race condition with the consumer update.
by making the call to update_consumer synchronous, we are sure that all new/removed consumers are _at least scheduled_ for start/termination before sending additional messages to the AMQPConsumerRegistry
Fixes #
```docs
```
=> test(te): avoid 6 seconds sleep

apps/astarte_data_updater_plant/config/test.exs, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_pipeline_supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/vmq_plugin.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/vmq_plugin/behaviour.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/rpc/vmq_plugin/client.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater_test.exs, apps/astarte_data_updater_plant/test/support/mocks.ex, docker-compose.yml
Reworks the RPC strategy between `DUP` and `VerneMQ`, using `GenServer` calls instead of the `astarte_rpc` library
=> refactor(DUP): VerneMQ RPC

apps/astarte_realm_management/test/astarte_realm_management/jwt_test.exs, apps/astarte_realm_management/test/astarte_realm_management/realm_test.exs, apps/astarte_realm_management/test/support/helpers/database.ex
Based on #1211 
Adds property based testing for realm and jwt functionalities in Realm management:
- RM shoud be able to retrieve and update the `JWT PEM` certificate
- RM should be able to retrieve the `device_registration_limit` and `datastream_maximum_storage_retention` of a realm
=> test(RM): test realm and jwt functionalities in RM

apps/astarte_appengine_api/test/test_helper.exs, apps/astarte_data_updater_plant/test/test_helper.exs, apps/astarte_housekeeping/test/test_helper.exs, apps/astarte_housekeeping_api/test/test_helper.exs, apps/astarte_pairing/test/test_helper.exs, apps/astarte_pairing_api/test/test_helper.exs, apps/astarte_realm_management/test/test_helper.exs, apps/astarte_realm_management_api/test/test_helper.exs, apps/astarte_trigger_engine/test/test_helper.exs
this reduces cluttering during tests in a substantial way, while still showing logs in case of a failed test (and in an organized way).
unfortunately this won't remove _all_ logs, as the logs from the `application.ex` starting will still be shown as not part of the exunit processes.
```docs
```
=> test: use capture_log

apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_message_consumer/amqp_message_consumer.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine/amqp_consumer/amqp_message_consumer/impl.ex, apps/astarte_trigger_engine/test/amqp_consumer/amqp_message_consumer_test.exs, apps/astarte_trigger_engine/test/support/cases/fake_rabbit_pool.ex, apps/astarte_trigger_engine/test/support/helpers/amqp_message_consumer.ex
adds unit tests for amqp_message_consumer.
mimic has been used for RabbitMQ because, although it provides a behavior, this would make existing processes fail crash for unset expectations, when we only really want to use `FakeRabbitMQ` in a subset of the tests
depends on #1215
```docs
```
=> refactor(te): amqp_message_consumer's core extraction for units

apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/trigger_policy_view.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/policies/policy_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_policy_controller_test.exs, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock.ex
- Improve testing coverage for realm management api, by removing unused trigger policy view as it is actually handled by `trigger_policy_already_present` and not `already_installed_policy`
- Fix extension mistake in `trigger_policy_controller_test.ex` file as it was not being executed since it was named with `.ex` extension instead of `.exs`
- Add property based testing for trigger policies
- Refactor context tests to test functions in isolation
- Update `execute_rpc` function to properly support synchronous calls
=> test(RM API): Expand and refactor trigger policy testing

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/test/astarte_realm_management/device_test.exs, apps/astarte_realm_management/test/astarte_realm_management/interfaces_test.exs, apps/astarte_realm_management/test/support/helpers/database.ex
Tests device deletion in Realm Management `Engine` module with property based testing. The actual deletion is carried out by another module (`DeviceRemover`) hence here the only thing to test is that RM correctly puts a new entry in the `deletion_in_progress` table in the DB, so that the device remover can then query the database and handle the deletion asyncronously (with DUP). Tests of that module will appear in another PR.
=> test(RM): test device deletion

apps/astarte_trigger_engine/test/astarte_trigger_engine_web_test.exs, apps/astarte_trigger_engine/test/support/helpers/database.ex
add `device_registration_limit` realm field to the database schema so that the query for the health check doesn't crash
this field was actually introduced in astarte 1.2 but not documented
```docs
```
=> test(te): fix health check

apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/device_controller_test.exs
Add a call to `DB.put_jwt_public_key_pem/2` in the test `setup` block to explicitly register the JWT public key for the test realm. Previously, the absence of a public key caused `:jose_jwk.from_pem/1` to raise a `FunctionClauseError` due to receiving `nil`. This happened because `VerifyHeader.get_secret/1` attempted to fetch the public key but found none, leading to failing controller tests involving authenticated requests.
=> test(RM API): Fix test flakiness by ensure JWT public key is set

.github/workflows/astarte-apps-build-workflow.yaml, apps/astarte_appengine_api/lib/astarte_appengine_api/rooms/amqp_client.ex
AMQPClient needs an exchange `events_exchange_name` to be declared, otherwise the queue binding fails and the whole application fails to start.
this was mitigated in CI with a custom exchange declaration and in production by having DUP or TE declare this exchange for AE before it could start successfully.
while for queues it's documented (eg [here](https://www.rabbitmq.com/tutorials/amqp-concepts#queues)) that "The declaration will have no effect if the queue does already exist and its attributes are the same as those in the declaration", this appears to be never explicitly stated to also be the case for exchanges.
however, in astarte we're already declaring this exchange twice:
- once in [trigger engine](https://github.com/astarte-platform/astarte/blob/d5ed3c0a6c1af3b620a436ae506462c75653 …
=> fix(ae): properly declare needed exchanges

apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/trigger.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/amqp_action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/http_action_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/trigger_test.exs
- Replaced the deprecated MFA (`{Module, :function, args}`) in the `:with` option of `cast_embed/3` for the `:amqp_action` field with an anonymous function, as recommended by Ecto 3.12.5.
- Fix extension mistake in `amqp_action_test.ex` file as it was not being executed since it was named with `.ex` extension instead of `.exs`
- Add amqp and http header size tests, with default and custom error messages
- Add tests for recognizing atom keys not just string keys
- Remove unused aliases
- Add module tags
=> test(RM API): Expand and refactor trigger actions testing 

apps/astarte_housekeeping/coveralls.json
remove helper files from test coverage
remove also release_task because it's only a wrapper for queries and migrator
=> HK remove helper files from test coverage

apps/astarte_housekeeping/priv/migrations/astarte/0001_drop_astarte_schema_table.sql, apps/astarte_housekeeping/test/astarte_housekeeping/migrator_test.exs, apps/astarte_housekeeping/test/helpers/db_test_helper.ex
Rationalize and expand migrator test
Edit test helper with new functions (83.7% coverage for the file)
Edit existing migration file to ensure process does not crash on unexpected db version
=> Hk new migrator tests 

apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex
the individual validation can return `{:error, reason}`, which was not handled by the object validation and lead to a crash
fix this by properly declaring it in the `else` block
```docs
```
=> fix(appengine): don't crash on invalid object update values

doc/pages/architecture/090-database.md
the database schemas show many instances of `text` type where the values are really declared as `varchar` in hk/rm code
partial backport of https://github.com/astarte-platform/astarte/pull/968 with added `individual_datastreams` changes
this changes would also be valid for release-1.0 but was based on 1.1 because 1.0 is deprecated
partially fixes #1227
```docs
```
=> doc: update database schemas

apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/test/astarte_realm_management/interfaces_test.exs
Fixes the usage of an old behavior of `Repo.fetch_all` causing a crash each time a user requested the listing of all available interfaces.
=> fix(RM): avoid crashing on interface list

apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/test/support/helpers/astarte_housekeeping_mock.ex
The `realm_exists?` function is not used anywhere in the codebase and has been removed to reduce clutter and improve maintainability. This change has no effect on functionality and is purely a cleanup.
=> chore(HK API): Remove unused `realm_exists?` function

apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/interface_controller_test.exs, apps/astarte_appengine_api/test/test_helper.exs
Adds tests for interface update and retrieval with optional `keep_milliseconds` parameter
=> test(AE): test for optional `keep_milliseconds` parameter

apps/astarte_appengine_api/coveralls.json, apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex, apps/astarte_appengine_api/lib/astarte_appengine_api/device/queries.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/fallback_controller.ex, apps/astarte_appengine_api/lib/astarte_appengine_api_web/views/error_view.ex, apps/astarte_appengine_api/test/astarte_appengine_api_web/controllers/interface_controller_test.exs, apps/astarte_appengine_api/test/support/cases/device.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/test/support/database_test_helper.exs
Astarte documentation reports an optional field of properties interfaces called `allow_unset`.This field should allow or forbid for interface value unset.
Up to now this field was not checked, and interfaces with `allow_unset: false` or `allow_unset: nil` were able to unset such properties.
This PR introduces such checks both in server owned interfaces (trough appengine) and in device owned interfaces (trough data updater plant).
Tests in both services are also added/edited accordingly:
- In appengine a deletion property is checked:  when unsetting properties with `allow_uset: true` the API should return `204` (no content) as HTML code. Instead, when `allow_unset` is `false` the server should answer with a `400` status code (bad request)
- In DUP the old _happy path_ test is updated to …
=> fix: make `unset_property` work

codecov.yaml
Old `codecov.yaml` file took precedence in codecov report generation and did not contain all the components definitions and new rules, this commit removes that file and uses the new `codecov.yml` file convention
For context: https://docs.codecov.com/docs/components
=> ci: remove old files

apps/astarte_appengine_api/test/astarte_appengine_api/device/device_v2_reading_test.exs, apps/astarte_appengine_api/test/support/helpers/database.ex, apps/astarte_appengine_api/test/support/helpers/database_v2.ex, apps/astarte_appengine_api/test/support/interface_values_retrieveal_generators.ex
allows downsampling options if:
- an individual interface is downsampable
- an object interface's downsample keys are overridden from params
the final step would be allowing all downsampable object interfaces
without overrides from params, but currently this would mean checking
that an object key does not contain any `nil` value.
this would become easier to implement if we implemented nil handling
in exlttb
remove warnings by dropping unused alias and module attribute
~~depends on #1271~~
```docs
```
=> test(appengine): add downsampling to interface value options gen

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/interface.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/time_based_actions.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/time_based_actions_test.exs, apps/astarte_data_updater_plant/test/support/helpers/database.ex
Currently, `impl.ex` contains the `execute_time_based_actions/2` function which collects logic for refreshing device state. It is not tested. Therefore, the following functions should be moved to a different module, and each one tested in isolation:
- `reload_groups_on_expiry/2`
- `purge_expired_interfaces/2`
- `reload_device_triggers_on_expiry/2`
- `reload_device_deletion_status_on_expiry/2`
- `reload_datastream_maximum_storage_retention_on_expiry/2`
=> refactor(DUP): move time-based actions away from impl.ex and test them separately

.github/codecov.yml, .github/workflows/astarte-apps-build-workflow.yaml
CI configuration was never meant to use flags but codecov somehow misundertood us (the _somehow_ has a name and an address, and are mine)
This removes flags when uploading and should force codecov to read components configuration
Also changes path definition to better fit codecov example
- codecov components docs: https://docs.codecov.com/docs/components
- codecov example: https://github.com/codecov/example-components
=> ci: remove flags config

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/cache.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/cache_test.exs, apps/astarte_data_updater_plant/test/test_helper.exs
- Fix the expiry logic in `fetch/2` and `has_key?/2` by introducing a clearly named `expired?/1` predicate. This reverses the previous logic, making the intent explicit and avoiding double negatives
- Add complete test suite for the `Cache.ex` module, which previously lacked any test coverage.
=> DUP: fix expiry check and add tests

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/interface_test.exs, apps/astarte_data_updater_plant/test/support/cases/device.ex, apps/astarte_data_updater_plant/test/support/helpers/database.ex, apps/astarte_data_updater_plant/test/support/interface_update_generators.ex
This adds utilities to test data updater plant `Core.Interface` module.
- Moves state setup into a separate `setup_all` block, getting the state from the `data_updater` once
- syncs `interface_id`s with the database
- adds utilities to insert data into `individualk_properties` table
- adds interface update generators, copying it from `AppEngineAPI`
- tests for `prune_interface` in `Core.Interface`
=> test(DUP): add setup for dup tests and test `prune_interface`

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/interface_test.exs, apps/astarte_data_updater_plant/test/support/cases/device.ex, apps/astarte_data_updater_plant/test/support/helpers/database.ex, apps/astarte_data_updater_plant/test/support/interface_update_generators.ex
Based on #1293 
Adds test for `resolve_path/3` in `Core.Interface` module, testing that given a path and an interface a coherent endpoint is returned
=> test(DUP): path resolution

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/deletion_scheduler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/time_based_actions.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/time_based_actions_test.exs
Standardize the format of having only the `Queries` module know about `keyspace_name` and `astarte_instance_id`
fixes two instances in which this was applied BOTH in application code and in the queries module
```docs
```
=> fix(dup): avoid applying `astarte_instance_id` twice

.github/codecov.yml, .github/workflows/astarte-apps-build-workflow.yaml
At some point while trying to understand codecov I seem to have read the documentation correctly; stating
Then dyslexia came in, and I moved everything to components
Now I'm here to make amend of my errors, taking everything back and reinserting flags in our CI, this should give us more consistent and understandable feedback on
- project coverage, computed according to the combined coverage of all astarte services coverage
- service coverage, computed with `mix coveralls`
- patch coverage
=> ci: move back to flags

.github/codecov.yml, .github/workflows/astarte-apps-build-workflow.yaml
- sets individual carryforward for flags
- updates codecov ci action to version `v5`
PRs should report the following informations:
- total poroject coverage
- patch coverage
- service coverage
=> ci: individually carryforward

.github/codecov.yml, .github/workflows/astarte-apps-build-workflow.yaml
Moves CI codecov configuration to use flags and a flag based coverage approach
Port forwards recent CI changes, namely PRs #1302 and #1298
=> forward port from `release-1.2`

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex
restore the behavior pre-1283 of having all du/queries queries be safe
```docs
```
=> fix(dup): use safe_fetch_one in queries

apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/time_based_actions_test.exs
Added missing test case to ensure proper behavior when `reload_datastream_maximum_storage_retention_on_expiry/2` encounters an error. Previously, the underlying repo functions did not properly handle such errors. After recent updates, this test confirms that the state remains unchanged when an error occurs.
```docs
```
=> test(DUP): Add missing raised error test for `reload_datastream_maximum_storage_retention_on_expiry/2

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/data_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/device.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/time_based_actions.ex
Attempting to refactoring DUP we noticed that a huge amount of the file is part of the data handling of a device (the `handle_data/5` function)
This PR moves the logic to a separate module and makes some cosmetic changes and minor refactoring intervention in other parts of data updater trying to reduce `impl.ex` size
=> refactor(DUP): drastically reduce `impl.ex`

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/data_handler.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/data_trigger.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/device.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/error.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/interface.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/trigger.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/impl.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/time_based_actions.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/device_test.exs, apps/astarte_data_updater_plant/test/test_helper.exs
Based on #1315 ~and #1313~
Up to now errors were handled in `handle_data/5` directly, with little to no testability
This refactors the code by
- providing error handling function testable separately
- move error handling where errors happen instead of the `else` branch of `handle_data/5`
- provide a general framework for message context and errors in data handling
=> refactor(DUP): better (and more testable) error handling

apps/astarte_housekeeping/lib/astarte_housekeeping/engine.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/rpc/handler.ex, apps/astarte_housekeeping/test/astarte_housekeeping/engine_test.exs, apps/astarte_housekeeping/test/astarte_housekeeping/rpc/amqp_server_test.exs, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/config.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/queries.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/realms/realms.ex, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/rpc/housekeeping.ex, apps/astarte_housekeeping_api/test/astarte_housekeeping_api/realms/realms_test.exs, apps/astarte_housekeeping_api/test/astarte_housekeeping_api_web/controllers/realm_controller_test.exs, apps/astarte_housekeeping_api/test/support/helpers/astarte_housekeeping_mock.ex, apps/astarte_housekeeping_api/test/support/helpers/astarte_housekeeping_mock_db.ex, apps/astarte_housekeeping_api/test/test_helper.exs
Replace the `delete_realm` function implementation with RPC with direct database access.
```docs
```
=> refactor(HK): Remove `delete_realm` RPC

apps/astarte_housekeeping_api/config/prod.exs, apps/astarte_housekeeping_api/lib/astarte_housekeeping_api_web/endpoint.ex
Logs did not show the standard Phoenix `request_id`, making it impossible to correlate the request with its response. Include also more information that is standard among other Astarte services (e.g. method, request_path).
Moreover, make sure that log entries are not duplicated.
Fixes #
```docs
```
=> HK API: correlate request and response

apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/interfaces.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/queries.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/interface_controller.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/auth/auth_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/device_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_version_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/realm_config_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_policy_controller_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/version_controller_test.exs, apps/astarte_realm_management_api/test/support/cases/conn_case.ex, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock.ex, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock_db.ex
Moves `fetch_interface` from RealmManagement to  the `API` frontend service. This is part of a series of PRs trying to refactor our services and rationalise our infrastructure.
- `RealmManagement.API` service now has the `RealmManagement` test and dev dependency
- The `fetch_interface` query gets moved to the frontend service
- Old tests are skipped, I found this approach simpler instead of trying to make everything work for tests that should disappear in a couple of weeks
- New tests have been put in place, adding support for astarte test cases (database and conn)
=> refactor(RM): move `fetch_interface` to the RM frontend

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/policies/policies.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/policies/queries.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/triggers/policies/policy_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_policy_controller_test.exs, apps/astarte_realm_management_api/test/support/helpers/astarte_realm_management_mock.ex
- Replace the `get_trigger_policies_list` function implementation using RPC with direct database access
- Remove `get_trigger_policies_list` RPC as it is not used by any component
```docs
```
=> refactor(RM): remove `get_trigger_policies_list` RPC

apps/astarte_realm_management/lib/astarte_realm_management/engine.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/lib/astarte_realm_management/rpc/handler.ex, apps/astarte_realm_management/test/astarte_realm_management/rpc/handler_test.exs, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/interfaces.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/interfaces/queries.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/rpc/realm_management.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api/interfaces/interfaces_test.exs, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/interface_version_controller_test.exs
Replace the `get_interface_versions_list` function implementation using RPC with direct database access
```docs
```
=> refactor(RM): Remove get_interface_versions_list RPC 

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/data_handler.ex
the handling of the unset of a property crashed because of a wrong match, It is now fixed to discard the message, not update the stats and ask for a clean session (reset the device connection).
=> fix(dup): do not crash when handling unset of a property

apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/triggers.ex, apps/astarte_realm_management_api/test/astarte_realm_management_api_web/controllers/trigger_controller_test.exs
https://github.com/astarte-platform/astarte/pull/1237 changed the get_trigger function to now return the action struct, but to do so it uses keys: atoms! in the Jason.decode call, which is also applied recursively to the static headers, and may fail if the header does not have a pre-existing atom.
by manually assigning each field to the struct, we avoid this problem
I have read [CONTRIBUTING.md](https://github.com/astarte-platform/astarte/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/astarte-platform/astarte/CODE_OF_CONDUCT.md)
I have added to [CHANGELOG.md](https://github.com/astarte-platform/astarte/CHANGELOG.md) relevant changes and any other user facing change
I have added or ran the appropriate tests
What this PR does / why we need it:
Which issue(s) this PR fixes: …
=> refactor(rm): manually convert action map to action struct

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/device.ex
Previously, the device process could crash when handling introspection if a new interface was provided. This should fix it as the fetch of interface major can fail and therefore not trigger `interface_minor_update` triggers
=> fix: handle missing interface in introspection

apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/core.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/queries.ex
fixes `fetch_interface` duplicated in the queries of the `Triggers` query module, with wrong aliases, making realm management api crash when installing a new trigger.
=> fix(rm) crash during trigger installation

apps/astarte_realm_management_api/lib/astarte_realm_management_api/auth/auth.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/device_removal/core.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/realm_config/queries.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/action.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/amqp_action.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/http_action.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api/triggers/trigger.ex, apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/plug/verify_header.ex
Based on #1378 
Fixes the majority of `mix dialyzer` errors, leaving one error in `KvStore`  insertions
This also removes the unused `rpc` modules to interact with the backend service as nobody is using it
=> chore(rm): address (the majority of) `dialyzer` errors

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/core/data_handler.ex
Corrected argument format for Core.Error.handle_error call
- Corrected  format of `error` argument  for Core.Error.handle_error call
```docs
```
=> fix(DUP): Fix argument format

.github/workflows/astarte-apps-build-workflow.yaml
runs `mix dialyzer` in ci and does not discard its errors
=> ci: activate dialyzer

apps/astarte_appengine_api/README.md, apps/astarte_data_updater_plant/README.md, apps/astarte_housekeeping/README.md, apps/astarte_pairing/README.md, apps/astarte_realm_management/README.md, apps/astarte_trigger_engine/README.md
Adds more first-hand informations on components on how to build them, lint them and test them directly in the REAMDEs.
=> chore: update readmes

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_pipeline_supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/producers_supervisor.ex
Moves `AMQP` producer processes into their own module. This is a first step in the direction of handling amqp producers configuration and initialization trough their own modules.
=> refactor(dup): move `AMQP` producer processes

apps/astarte_pairing/lib/astarte_pairing_web/controllers/agent_controller.ex, apps/astarte_pairing/lib/astarte_pairing_web/controllers/device_controller.ex, apps/astarte_pairing/lib/astarte_pairing_web/telemetry.ex
- Updated the telemetry event name from [:astarte, :pairing, :api, :request]
to [:astarte, :pairing, :request] to match the defined metric names:
- astarte.pairing.request.count
- astarte.pairing.request.request_body_bytes
- astarte.pairing.request.response_body_bytes
-  Expanded metrics to count number of verify_credentials and
unregister device requests
```docs
```
=> refactor(pairing): expand pairing metrics

apps/astarte_realm_management/lib/astarte_realm_management/device_removal/core.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex, apps/astarte_realm_management/test/astarte_realm_management/device_removal/core_test.exs
previously, devices with invalid introspection would make the device removal process crash because the interface was not found.
by using the existing function from astarte data access, we avoid this crash by simply ignoring interfaces that don't exist
Fixes #
```docs
```
=> fix(rm): avoid crash when deleting devices with invalid introspection

apps/astarte_realm_management/lib/astarte_realm_management/device_removal/device_remover.ex, apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
As the device is guaranteed to be deleted at least once, it may happen
that a crash happened between the device cancellation and the deletion
in progress entry cancellation.
Account for this possibility and let the process terminate successfully
after a cleanup
=> fix(rm): ensure devices are cleaned up after being deleted

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_triggers_producer.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/producers_supervisor.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/triggers_handler.ex
Previously `AMQP` triggers published on exchanges in the same vhost as all other astarte exchanges. This was no bliss but only a curse, as we relied on complex regexp for permission management in rabbitmq to allow clients access only to their exchanges. This PR sets the ground to solve this devops issue by moving amqp exchanges into their own vhost (if astarte is configured to do so, defaulting to the current behavior).
The `ProducersSupervisor` initializes two pools of rabbitmq connections trough `ExRabbitPool`: one for the astarte internals and one for amqp triggers. The connection pool for triggers is configured to use the vhost provided by astarte trough environment variables
in trigger handler if the target exchange is nil (which only happens for `astarte_event`s) the publication …
=> feat(dup): separate amqp trigger exchanges in their own vhost

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/config/telemetry_type.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/telemetry.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/telemetry/database_events.ex
Bounces xandra telemetry events, adding visibility on database errors and exceptions.
=> deat(dup): support xandra telemetry bounce

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/data_updater/queries.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/core/device_test.exs, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/data_updater/queries_test.exs, apps/astarte_realm_management/test/astarte_realm_management/device_test.exs, apps/astarte_realm_management/test/test_helper.exs
previously, updates were changed from upserts to normal updates to
avoid re-inserting previously deleted values. This introduced a bug
because Ecto would complain about stale values if the update did not
modify the struct in the database. fix this by setting the appropriate
flag (`allow_stale`)
regression tests for previous fixes have been added to prevent this
from happening again
the update functions now return `:ok`. this does not change the usage
of the functions as the return value was just discarded, but returning
the deletion in progress entry when the value did not exist in the
database is incorrect
=> fix(dup): crash when performing updates of deleted values

apps/astarte_housekeeping/lib/astarte_housekeeping/config.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/config/replication_strategy_type.ex, apps/astarte_housekeeping/lib/astarte_housekeeping/realms/queries.ex, apps/astarte_housekeeping/test/astarte_housekeeping/realms/queries_test.exs
replace custom "simple" and "network" names with "SimpleStrategy" and "NetworkTopologyStrategy"
this also aligns the naming with realm creation
Fixes #
```docs
```
=> refactor(housekeeping)!: use default replication naming from scylladb

apps/astarte_appengine_api/lib/astarte_appengine_api_web/telemetry.ex, apps/astarte_data_updater_plant/lib/astarte_data_updater_plant_web/telemetry.ex, apps/astarte_housekeeping/lib/astarte_housekeeping_web/telemetry.ex, apps/astarte_pairing/lib/astarte_pairing_web/telemetry.ex, apps/astarte_realm_management/lib/astarte_realm_management_web/telemetry.ex, apps/astarte_trigger_engine/lib/astarte_trigger_engine_web/telemetry.ex
some telemetry names had "count" mistakenly named "conut"
Fixes #
```docs
```
=> fix: typos in telemetry names

tools/astarte_e2e/lib/astarte_e2e/data_trigger.ex, tools/astarte_e2e/lib/astarte_e2e/device.ex, tools/astarte_e2e/lib/astarte_e2e/device_deletion.ex, tools/astarte_e2e/lib/astarte_e2e/volatile_trigger_roundtrip/executor.ex
treat the device module as a wrapper around the sdk's device module
always wait for connection before proceeding. solves an issue with volatile triggers trying to be installed while the device is not yet connected
Fixes #
```docs
```
=> refactor(e2e): don't start volatile trigger client with the device

.github/workflows/astarte-end-to-end-test-workflow.yaml, tools/astarte_e2e/lib/astarte_e2e/application.ex, tools/astarte_e2e/lib/astarte_e2e/config.ex, tools/astarte_e2e/lib/astarte_e2e/config/jwt_public_key_pem_type.ex, tools/astarte_e2e/lib/astarte_e2e/realm.ex, tools/astarte_e2e/lib/astarte_e2e/task_scheduler.ex
Create Realm directly in astarte_e2e instead of a separate CI step.
Create realm inside astarte_e2e tool, instead of CI.
Fixes #
=> refactor(e2e): move realm creation to astarte_e2e

apps/astarte_data_updater_plant/lib/astarte_data_updater_plant/amqp_events_producer.ex, apps/astarte_data_updater_plant/test/astarte_data_updater_plant/amqp_events_producer_test.exs, apps/astarte_data_updater_plant/test/test_helper.exs
the refactor in b57bf46 broke the reconnection logic by removing the handle of the reconnection message. this also explains why the arguments in the `Process.send_after` call have been out of order for months without anyone noticing.
this logic is now reintroduced with the following modifications:
- we do not reconnect if we're already connected to a channel. this is needed to prevent subsequent `:init` messages from making the producer unusable: this would result in a call to `ExRabbitPool.checkout_channel` when all channels in the pool are already allocated, resulting in an `:out_of_channels` error which will recursively schedule a reconnection and fail.
- a regression test has been added for the feature. to avoid the test being 20 seconds long, the backoff has been set to 0 in tests
=> fix(dup): correctly reconnect to amqp after a connection loss

doc/pages/architecture/090-database.md
This PR introduces documentation for the optional ASTARTE_INSTANCE_ID variable. The variable defaults to an empty string for backward compatibility, but can be set to improve namespace isolation when running multiple Astarte instances on a shared database. The Operator fully supports this variable and ensures that keyspace names remain within valid length limits.
=> docs: add description for ASTARTE_INSTANCE_ID variable

.github/workflows/astarte-apps-build-workflow.yaml
dialyzer is smart enough to avoid rebuilding cache for already built modules
fixes issue with dialyzer step failing for local dependencies because they didn't get rebuilt
=> ci: don't skip dialyzer plt build with cache hit
